### ISSUE TITLE
Smarter labels

### ISSUE THREAD

**Issue by ENT8R** [ENT8R/streetcomplete-mapstyle#1]
The labels of major cities should be displayed larger than the labels of small villages.

**Comment by westnordost** [comment]
(Or labels of larger cities being displayed at lower zoom levels, villages later.)

**Comment by matkoniecz** [comment]
> (Or labels of larger cities being displayed at lower zoom levels, villages later.)

It is already done as part of processing mapzen data. See for example https://mapzen.com/tangram/play/?#8.7500/49.6806/19.3248

to keep good label styling in situations like https://mapzen.com/tangram/play/?#9.0000/50.1954/19.5735 I added larger labels for `population: { min: 50000 }` locations (and filtered out `kind: [region, county, state]` labels - covered by #18

**Comment by westnordost** [comment]
So this is done?

**Comment by ENT8R** [comment]
Yes, I think we did what we can do...
