### ISSUE TITLE
Bridges structure not displayed correctly

### ISSUE THREAD

**Issue by canu1337** [ENT8R/streetcomplete-mapstyle#101]
Hello,

I think that there is an issue in the way bridges are displayed. The bridge structure itself is not displayed, only the ways on it. As such, some bridges have "holes" in them.

**How to Reproduce**
Here is an example, The "Pont Mayou" in Bayonne. On [openstreemap.org](https://www.openstreetmap.org/#map=19/43.49225/-1.47398), it looks like this, with the bridge clearly visible.
![image](https://user-images.githubusercontent.com/4050064/125209701-fa78e500-e29a-11eb-9ddd-883fedad9c46.png)
On StreetComplete, it looks like this, the bridge structure is not visible, and I actually thought of an OSM data error.
![image](https://user-images.githubusercontent.com/4050064/125209717-1aa8a400-e29b-11eb-9f36-a3d58b8c367c.png)

**Versions affected**
v32.1

**Comment by westnordost** [comment]
The vector tile layer from Jawg.io doesn't have this information, see:
https://www.jawg.io/docs/apidocs/maps/streets-v2/#layer-reference

I'll just ping @Joxit here, in case he wants to consider to include `man_made=bridge` for the jawg.io tilesm, or not but for now it is can not / will not fix.

**Comment by Joxit** [comment]
Hi there, 

If I understand correctly, the missing part you want is the polygon under bridge ways? The grey part on osm? 

You may share the official documentation link here https://www.jawg.io/docs/apidocs/maps/streets-v2/#layer-reference

**Comment by matkoniecz** [comment]
@westnordost I edited out the link, so it directs to a public docs. Hopefully that is OK

> If I understand correctly, the missing part you want is the polygon under bridge ways? The grey part on osm?

Yes, bridge outline. See https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dbridge

**Comment by Joxit** [comment]
Hello, I just added man_mande=bridge to our list. This should be visible in 24 to 48 hours. You will need to change your style, the new class is `bridge` with the type `bridge` in `structure` layer.

Checkout [`structure`](https://www.jawg.io/docs/apidocs/maps/streets-v2/#structure) layer reference.
