### ISSUE TITLE
Display railway platform numbers

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/streetcomplete-mapstyle#102]
During recent mapping of railway station area I really missed display of code of railway platforms.

If Jawg makes it possible then displaying `ref` on `railway` platform would be helpful in places like https://www.openstreetmap.org/way/35301192#map=19/51.09810/17.03716

(I ended using Vespucci for that)

**Comment by ENT8R** [comment]
Not possible with Jawg, as they don't supply this information (i.e. platforms and additional information like ref). In fact, Jawg only shows the name of the train station and of course any buildings/ways belonging to the station.
