### ISSUE TITLE
motorway_link should have color used by motorway and trunk

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/streetcomplete-mapstyle#103]
Right now it looks silly and like wrong OSM data and on zooming out it seems that there are gaps in case of T junctions

Probably trunk_link is also affected

https://www.openstreetmap.org/#map=16/50.0129/20.0638

![screen02](https://user-images.githubusercontent.com/899988/130583865-4a174962-8174-4606-81c7-b43c7a3966f7.png)
![Screenshot_20210824-102613](https://user-images.githubusercontent.com/899988/130588270-3b1f55f6-e46b-4d36-90f5-ca14b04deebb.png)

**Comment by westnordost** [comment]
Agree

Am 24. August 2021 10:58:21 MESZ schrieb Mateusz Konieczny ***@***.***>:
>Right now it looks silly and like wrong OSM data and on zooming out it
>seems that there are gaps in case of T junctions
>
>https://www.openstreetmap.org/#map=16/50.0129/20.0638
>
>![screen02](https://user-images.githubusercontent.com/899988/130583865-4a174962-8174-4606-81c7-b43c7a3966f7.png)
>![Screenshot_20210824-102613](https://user-images.githubusercontent.com/899988/130588270-3b1f55f6-e46b-4d36-90f5-ca14b04deebb.png)
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/streetcomplete-mapstyle/issues/103

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by ENT8R** [comment]
I am unsure whether it might be a good idea to also display them using a smaller width. IMO this looks good for connections between motorways/trunks and other roads, but connections between motorways and other motorways may look odd in some cases, especially as these connecting roads often consist of more than one lane.

---

<h4 align="center">Motorway connecting with a different road</h4>
<p align="center">
<img src="https://user-images.githubusercontent.com/25306497/131220137-1fbd5adf-c706-451d-9c22-1a3516540799.jpg" width="400px"> <img src="https://user-images.githubusercontent.com/25306497/131220138-8e31fe60-6149-4363-b6dc-5649a7df09e4.jpg" width="400px">
</p>

<h4 align="center">Motorway connecting with another motorway</h4>
<p align="center">
<img src="https://user-images.githubusercontent.com/25306497/131222222-994d1d1f-de6c-4ddb-baa2-b0aef323f276.jpg" width="400px"> <img src="https://user-images.githubusercontent.com/25306497/131222225-555b4f9b-745c-488d-b2f6-153fa445e604.jpg" width="400px">
</p>

**Comment by westnordost** [comment]
I thikn that's ok. Slip roads are far more frequent than motorway links.

**Comment by matkoniecz** [comment]
smaller width looks weird on T-shaped motorway junctions, but on far more often slip roads wide _link looks extremely bad (based on provided examples)
