### ISSUE TITLE
Maybe railways in dark mode are too prominent

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/streetcomplete-mapstyle#107]
As one of people new to SC pointed out -railways are really, really, really prominent in night mode. To the point of being distracting.

Maybe reducing their prominence a bit and making roads a bit more visible would be a good idea?

(I am never using night mode, but after looking at it - I agree with that)

Maybe my city is more impacted due to tram lines and decent railway network?

![screen03](https://user-images.githubusercontent.com/899988/136711775-4e2a5266-4c57-4198-90f9-0703683a49d7.png)
https://www.openstreetmap.org/#map=15/50.0225/19.9794

**Comment by mnalis** [comment]
I sometimes use night mode in SC (evening/night) and I absolutely agree, it hurts. 
Similar situation is with major highways which get painted in bright cyan in dark mode.

**Comment by Helium314** [comment]
I agree, it's quite annoying... but easy to fix if this is wanted: https://github.com/streetcomplete/streetcomplete-mapstyle/issues/84#issuecomment-1120172659
