### ISSUE TITLE
Render natural=grassland like landuse=grass (impossible, missing in Jawg)

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/streetcomplete-mapstyle#108]
For example https://www.openstreetmap.org/way/328237209

https://www.openstreetmap.org/way/328237209 is rendered

I think that making distinction in rendering between this two tagging is pointless.

PS maybe landuse=construction rendering would be a good idea?

**Comment by matkoniecz** [comment]
It requires changes only on Jawg branch. Or maybe it is missing from Jawg tiles?

`landuse=construction` appears to be rendered in Thunderforest branch already.

![screen05](https://user-images.githubusercontent.com/899988/137092229-7beb51a3-6922-4d36-9a3e-d02231d66e2d.png)

**Comment by matkoniecz** [comment]
Closing this and pinging @Joxit , in case he wants to look into that.

(hopefully it is fine?)

`landuse=construction` data is also outright missing - see https://www.openstreetmap.org/way/825748122

![screen07](https://user-images.githubusercontent.com/899988/137094120-b74cbfc0-01ee-4a3e-a177-92443a4a4677.png)
![screen06](https://user-images.githubusercontent.com/899988/137094129-ce5283ee-4799-448f-9a7f-54f30a4618ce.png)

**Comment by Joxit** [comment]
Hello,

Thank you for your ping :smile:, you are right `natural=grassland` may be interesting in our tileset.
We will add this in the layer `landuse` with the class `grass`.

For now, IDK if we will add `landuse=construction`

**Comment by Joxit** [comment]
Can you assign me to this issue ?

**Comment by westnordost** [comment]
Come to think of it, I maybe discovered a very minor bug in jawg, will check it quickly

**Comment by Joxit** [comment]
Hello, I just added `natural=grassland` to our list. This should be visible in 24 to 48 hours. You won't have to change your style, it will use the class `grass` with the type `grassland`.

Checkout [`landuse`](https://www.jawg.io/docs/apidocs/maps/streets-v2/#landuse) layer reference.

**Comment by matkoniecz** [comment]
Great, thanks! So I will close this as it will become fixed soon without further action.

`landuse=construction` also would be nice (I noticed that data is missing in OSM based on StreetComplete display, open Vespucci, discovered that `landuse=construction` was mapped)

**Comment by Joxit** [comment]
`landuse=construction` is not yet in my list of elements to add, IDK if it will be interesting for 80% of our customers. You can create a new issue and assign it to me if you want :smile:
