### ISSUE TITLE
open sans font seems to be unused

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/streetcomplete-mapstyle#11]
Maybe it's font files and font definitions may be removed?

**Comment by ENT8R** [comment]
I just copy pasted them in case we need it later. Or do you think one font is enough?

**Comment by matkoniecz** [comment]
I see no reason to display part of labels in one font and party in other.

One thing that may be worthwhile to check is to test whatever currently used Montserrat works well with Arabic, Japanese, Korean etc etc labels.

**Comment by ENT8R** [comment]
> I see no reason to display part of labels in one font and party in other.

Yes that's right. I will remove them. We cann add them later again if we need them...
