### ISSUE TITLE
Plazas are not rendered correctly

### ISSUE THREAD

**Issue by westnordost** [ENT8R/streetcomplete-mapstyle#115]
The outline of plazas (highway=pedestrian etc, area=yes) are rendered as a normal road.

**Comment by matkoniecz** [comment]
It happens on certain zoom levels (maybe depending on area size?). As one zooms in, this changes.

**Comment by Helium314** [comment]
The change when zooming out can be significantly improved by setting min zoom in https://github.com/streetcomplete/streetcomplete-mapstyle/blob/2ecce80b365b2eea1e1351ad3abe5f8b355f9a5b/layers/land.yaml#L121
from 17 to 14 (at this level also the road outlines disappear).

**Comment by westnordost** [comment]
PR welcome
