### ISSUE TITLE
Don't render building heights when building:part heights in a polygon are already rendered

### ISSUE THREAD

**Issue by wielandb** [ENT8R/streetcomplete-mapstyle#121]
I noticed that sometimes a building will have it's parts mapped as `building:part`s with levels associated. When the containing building does not have a `building:levels` associated with it, StreetComplete will ask for the building levels, resulting in the StreetComplete-Renderer showing it as a new extruded polygon over all building parts, visually "destroying" the intricately modeled building. 

This image is an example showing how a building without `building:levels` is correctly rendered and a building with it will be "overrendered" by the outline shape. 
![houseshapes](https://user-images.githubusercontent.com/29458682/157664702-c7d49204-b634-4b33-b68a-c8cf739403bf.jpg)

**Proposed solution:**

If possible, check if a building polygon collides/shares points with a polygon with `building:part=*;building:levels=*` 
and if so, do not extrude it.

**Comment by matkoniecz** [comment]
See https://github.com/streetcomplete/StreetComplete/issues/2205 especially https://github.com/streetcomplete/StreetComplete/issues/2205#issuecomment-749139738

> So anyway, I think it makes no sense to leave this issue open. There is nothing that can be done about that in this project. The map tile provider (Jawg) is informed about this problem, maybe they will do something about it, maybe they won't.
