### ISSUE TITLE
Render building polygon when number and street is not set

### ISSUE THREAD

**Issue by nklyshko** [ENT8R/streetcomplete-mapstyle#126]
**Use case**

I need to map buildings with levels data in big area, where determination of precise address is difficult. So I just disabled quests "What is the house number of this building?" and "What street does the (house) number belongs to?" and now I have direct access to quest "How many levels above the basement does this building have?". But buildings without number/street does not rendered as polygons on map and visual identification of certain building is hard.

![photo_2022-05-23_12-47-55](https://user-images.githubusercontent.com/7105938/169792812-c3216555-faaa-4864-9298-ac1d416e104c.jpg)

**Proposed Solution**

Enable rendering of buildings, which don't have number/street.

**Comment by matkoniecz** [comment]
> Enable rendering of buildings, which don't have number/street.

This buildings were likely recently added, buildings in general will appear.

Hmm, maybe SC should skip very recently added buildings in quests?

**Comment by westnordost** [comment]
Nah, according to @Joxit, jawg.io only lags behind the live data by a day or so, so these buildings should appear soon.

**Comment by matkoniecz** [comment]
Note that people reported longer delay due to caching of various sort (not investigated it properly but "mapped week ago, not appearing" is common)

**Comment by Joxit** [comment]
Hi there, @westnordost is right, this takes less than a week for sure.
Do you have fresh examples @matkoniecz ?
Maybe there is an in app cache?

**Comment by westnordost** [comment]
Yeah, there is an app cache. The app will always **attempt** to re-retrieve the tiles if they are older than 1 day, but the app will happily display the old tiles if the device is offline as long as the file still exists in the cache.

**Comment by riQQ** [comment]
See e.g. https://github.com/streetcomplete/StreetComplete/issues/2479 for more information.
