### ISSUE TITLE
Flickering water labels

### ISSUE THREAD

**Issue by Helium314** [ENT8R/streetcomplete-mapstyle#136]
Up to 45.1 labels on water appeared stationary when panning the map.
Starting with 45.2 the labels move sometimes, presumably to have them in view. Same thing happens for street names (also in previous versions), but nothing bad here.

Sometimes water labels jump around wildly and very rapidly. This is frequently noticeable when panning the map slowly, and sometimes also happens when the map is stationary.
I have the impression that it gets worse when quests or the own location is displayed. It's also sometimes possible to trigger this flickering when turning the phone with own location on screen (changes the view cone only, but this seems to be enough).

**Comment by matkoniecz** [comment]
I am pretty sure that I have seen this problem in 45.1 and earlier, also for water labels

**Comment by Helium314** [comment]
Maybe, but I just tried older version to see when it started, and I haven't seen it in a short test using 45.1 older versions. So even if it was there, it's much more frequent in newer versions.

**Comment by westnordost** [comment]
In the end, isn't this rather an issue of tangram rather than the mapstyle?

**Comment by Helium314** [comment]
Maybe it is, but at the same time it was probably triggered by a change in map style (didn't look up what exactly could have caused it) and I didn't notice any issues / bad placement of water labels previously.

**Comment by mnalis** [comment]
- possibly related: https://github.com/streetcomplete/StreetComplete/issues/4350

**Comment by Helium314** [comment]
The problem is https://github.com/streetcomplete/streetcomplete-mapstyle/blob/b13d78564f1be588c21bb14040f356a8693fa734/layers/labels.yaml#L28
removing the `20 +` makes the flicker go away.
Using other values instead of `20` changes label placement a little, but so far I always found at least some flickering for the values I tested.
Even when using `0` instead of `20`.

**Comment by westnordost** [comment]
Is "priority" maybe supposed to be a string in the end?

**Comment by Helium314** [comment]
At least for `place-labels` an integer works fine for the correct order...

**Comment by westnordost** [comment]
So weird... what is the pattern there...? Maybe the missing semicolon at the end is the issue?

**Comment by Helium314** [comment]
I think I already tried that, without effect

**Comment by Helium314** [comment]
> Is "priority" maybe supposed to be a string in the end?

... but maybe still it somwhow is?
`priority: function() { return ${20 + feature.scalerank} }` works (though I'm not even sure whether this actually results in a string as I didn't check how yaml parsing works...)
I didn't find any difference in label placement compared to `priority: function() { return feature.scalerank }` though

**Comment by westnordost** [comment]
Uh, what does `function() { return ${20 + feature.scalerank} }` in Javascript even do? (If this is a string placeholder like in kotlin, shouldn't there be quotes around that?)

**Comment by Helium314** [comment]
So this is javascript? I have no idea how yaml files are parsed and just did more or less "random" things.

**Comment by westnordost** [comment]
<img width="413" alt="Screenshot 2022-11-21 at 21 52 23" src="https://user-images.githubusercontent.com/4661658/203156027-8a57446d-35a3-4ea9-8120-8374fb3d96d3.png">
(In Firefox console)

**Comment by Helium314** [comment]
I wonder why there is no error message in SC / Tangram... and why this actually works better than the current version (for flickering and not hiding pins)

**Comment by matkoniecz** [comment]
> why this actually works better than the current version (for flickering and not hiding pins)

Maybe it is broken and therefore is not triggering broken functionality in Tangram? With two bugs negating each other?

**Comment by Helium314** [comment]
Looks like if value can't be parsed there is some fallback instead of a crash, and this fallback works better than the currently used value.

Anyway, `(20 + feature.scalerank).toString()` works, and strings are interpreted correctly (tested with place-labels)

**Comment by westnordost** [comment]
> Anyway, (20 + feature.scalerank).toString() works, and strings are interpreted correctly (tested with place-labels)

So, this is the fix to make it all work?

**Comment by Helium314** [comment]
With this change I am unable to reproduce both the flickering labels and the pin disappearing on the house linked in https://github.com/streetcomplete/StreetComplete/issues/4522#issuecomment-1290379346

**Comment by westnordost** [comment]
Do you plan to create a PR for this?

**Comment by Helium314** [comment]
I still don't have much time (and currently not even working Android Studio), but that's only a simple change to be done online...
Will do it tomorrow, of you can just commit it if you want it quicker.

**Comment by Helium314** [comment]
This should be fixed with #142
