### ISSUE TITLE
City walls obscure ways

### ISSUE THREAD

**Issue by Helium314** [ENT8R/streetcomplete-mapstyle#137]
When ways are on or near city walls, they are not visible on the map:
![Screenshot_20220929-183613_Street�Complete_Dev](https://user-images.githubusercontent.com/43007630/193089333-98bbca2d-e894-410f-a87c-121974612d58.png)
Interestingly this is better online using https://streetcomplete.github.io/streetcomplete-mapstyle/?provider=jawg
![Screenshot_20220929_183717](https://user-images.githubusercontent.com/43007630/193089325-c53b5275-5be6-4977-9463-9a3df0fe08f1.png)

And indeed the walls should be transparent as they use (building outline) color `rgba(185, 195, 217, .75)` 
In the app it looks like walls are only transparent if alpha is 0.5 or less.

So I think reducing alpha for building outline color (or having a separate style for city walls) would be useful for better visibility.

**Comment by westnordost** [comment]
You say it is a bug in tangram-es that only regards alpha if it is 0.5 or less?

**Comment by Helium314** [comment]
Maybe? It could also be some hardware / driver issue on my device...
Also way outline color looks rather different

**Comment by westnordost** [comment]
For me it is non-transparent too

**Comment by matkoniecz** [comment]
I remember transparency being ignored also earlier.

**Comment by Helium314** [comment]
This is solved with https://github.com/streetcomplete/StreetComplete/commit/da33482dcf1832c3f6e1d71b15a423c50420f04a
