### ISSUE TITLE
Roundabouts not recognised as oneway

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/streetcomplete-mapstyle#138]
@Joxit as far as I see, roundabouts are missing `oneway: true` being set.

It is result of a very silly idea of removing `oneway=yes` tag on `junction=roundabout` because it is treated as implied (see say https://wiki.openstreetmap.org/wiki/Tag:junction%3Droundabout )

Would it be possible to support this silliness add set `oneway: true` if `junction=roundabout` tag is present?

Effects is more visible in StreetComplete with overlays being enabled

https://www.openstreetmap.org/way/1052999274

![primary roandabout not detected as oneway - does not affect regular oneways](https://user-images.githubusercontent.com/899988/193233021-2701db3e-56bc-4ef1-9ad4-ef1ef1dcf418.png)

**Comment by westnordost** [comment]
`oneway=yes` or `oneway=-1`? (Apparently, `oneway=yes`) Yeah, it is really silly to not tag that explicitly... but alas, only ~20% of roundabouts have `oneway` tagged.

**Comment by Joxit** [comment]
Hi there, thank you for your message ! You are right we do not support `junction=roundabout` as oneways

This should be a quick change for us ! I will check this on Monday !

| count  |  oneway  |
|--------|------------|
|     61 | -1|
|   1323 | no|
|      2 | reversible|
| 208864 | yes|
| 865784 |  NULL |

**Comment by Joxit** [comment]
The update has been done, you should see the changes on the newly generated tiles.

**Comment by davidpnewton** [comment]
It's even worse than it being treated as implied. The Osmose site treat it is as "QA" issue. They actively encourage its removal. Just like they encourage the removal of lanes:forward as a tag on oneway roads. They don't seem to understand the concept that the additional tagging does no harm and contradicts nothing else so there is no reason to remove it.

**Comment by matkoniecz** [comment]
Yeah, Osmose has some really pointless or mildly harmful suggestions, and they WONTFIXed some related reports.

See also https://github.com/streetcomplete/StreetComplete/issues/4018 https://github.com/streetcomplete/StreetComplete/issues/3118 https://github.com/streetcomplete/StreetComplete/issues/4635

And https://github.com/streetcomplete/StreetComplete/issues/4478

**Comment by westnordost** [comment]
@matkoniecz can this ticket not be closed now due to it being solved on the jawg side?
