### ISSUE TITLE
Train platforms as multipolygons are not rendered correctly

### ISSUE THREAD

**Issue by FloEdelmann** [ENT8R/streetcomplete-mapstyle#139]
E.g. [this train platform](https://www.openstreetmap.org/relation/3277498) is a multipolygon. Only part of it is rendered in StreetComplete, while the whole platform is rendered in OSM Carto:

![grafik](https://user-images.githubusercontent.com/202916/200183763-698df632-bf8f-44a9-9448-69eba370749e.png)

![grafik](https://user-images.githubusercontent.com/202916/200183866-732d5d3b-1109-441e-9113-6bbe5f33c07d.png)

**Comment by matkoniecz** [comment]
Is this map style rendering platforms at all?

It seems to me that https://www.openstreetmap.org/way/242507879 https://www.openstreetmap.org/way/264448399 buildings are rendered, while platforms are completely ignored

**Comment by riQQ** [comment]
See also #105

**Comment by matkoniecz** [comment]
Thanks! So platforms are not shown at all, are not planned to be shown and cannot be shown anyway.

**Comment by FloEdelmann** [comment]
Ah, that's what confused me.
