### ISSUE TITLE
consider banning whosonfirst.mapzen.com labels

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/streetcomplete-mapstyle#14]
Mapzen data includes nonOSM data.

I am unsure whatever I am unlucky or overall data quality is low but whosonfirst.mapzen.com dataset at least in my region is full of malformed, duplicated and invalid labels (reported as https://github.com/tilezen/vector-datasource/issues/1410 https://github.com/whosonfirst-data/whosonfirst-data/issues/1008 https://github.com/whosonfirst-data/whosonfirst-data/issues/1022 https://github.com/tilezen/vector-datasource/issues/1418 ).

In addition this project seems to be quite slow to update, even with provided PRs - see https://github.com/whosonfirst-data/whosonfirst-data/pulls?page=2&q=is%3Apr+is%3Aopen

Malformed labels from external source are likely to be confusing for OSM editors - so maybe it would be a good idea to exclude them?

**Comment by ENT8R** [comment]
Yes, I think that this is a good idea too!

**Comment by matkoniecz** [comment]
It seems that filtering should be readded in https://github.com/ENT8R/streetcomplete-mapstyle/blob/master/layers/labels.yaml#L20
