### ISSUE TITLE
Open discussion: Reducing OSM sidewalk-clutter

### ISSUE THREAD

**Issue by westnordost** [ENT8R/streetcomplete-mapstyle#17]
![road1](https://user-images.githubusercontent.com/4661658/32135806-38fda65a-bc05-11e7-8bca-f2a10cf6686e.png)
Have a look at this: https://mapzen.com/tangram/play/?#18.50000/50.05670/19.94529

This is basically just an intersection of a big road with a small road (with a tram in the middle). See https://binged.it/2gIFXou Ignore the tram for now, there is another ticket for that.

I would like to reduce the clutter there, because it is
- not helpful for orientation
- actually perplexing
- doesn't reflect the reality. I.e. the sidewalks are attached to (/part of) the road and not independent ways. But on the map, it looks like that.
- irrelevant: the pedestrian does not need to know that there is an explicit sidewalk, he can see that from where he stands.

Of course, mapping sidewalks as separate ways when they are actually only separated by a curb is not really approved by the community, but that doesn't matter for us here, because this kind of sidewalk-mapping is widely used and the style needs to make do what is found "in the wild".

Now, this is a bit of a problem to solve, that is why I labeled this as an open discussion to collect and discuss ideas.

**Comment by westnordost** [comment]
One idea is to not display sidewalks at all. These separate-way sidewalks are usually tagged with `footway=sidewalk` but I am not sure if
- sidewalk-ways are actually tagged that way more or less consistently
- this information can be accessed in a mapzen-style

**Comment by westnordost** [comment]
Another (cumulative) idea is to try to display the street as broad as it really is: Access the `width` attribute of a road and if not present, assume 2m per lane and if `lanes` is not present, fall back to some default values depending on the road type. Also not sure if this is doable.

This would make roads where lanes are mapped as own ways ([like this](https://mapzen.com/tangram/play/?#18.25000/50.04843/19.93225)) also more clear.

We are used to, from the base map and other maps, that the "road importance", which often comes down to the number of lanes, is indicated by a different color. Most important roads are red, then through yellow down to white. But well, how about a different approach: Have the same color, but make broader roads actually broader (but only as broad as they really are).

**Comment by matkoniecz** [comment]
> Of course, mapping sidewalks as separate ways when they are actually only separated by a curb is not really approved by the community

AFAIK both mapping styles are widespread and there is no consensus what is better. 

> this information can be accessed in a mapzen-style

footway=sidewalk property is exposed, at least on some zoom levels - to check that open map style in https://mapzen.com/tangram/play/?scene=https://raw.githubusercontent.com/ENT8R/streetcomplete-mapstyle/master/style.yaml enable inspect (top-right) and click on a displayed object. pop-up with list of properties should appear

**Comment by matkoniecz** [comment]
> assume 2m per lane

lanes tag appears to not be present, appears to be tracked as low-priority idea on https://github.com/tilezen/vector-datasource/issues/1021

**Comment by matkoniecz** [comment]
In case of strong interest of using lane tag - in my experience vector-datasource is great at reviewing and merging PRs, but new version are rarely deployed (I am still waiting for my surface and access changes to be deployed).

**Comment by westnordost** [comment]
Okay, I think @matkoniecz is currently the expert on tangram map styles. I will create tickets based on his proposals here and close this.

**Comment by westnordost** [comment]
Some clutter will be fixed by #9
