### ISSUE TITLE
display different label categories

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/streetcomplete-mapstyle#18]
In addition - is it desirable to render kind: [region, county, state] labels? In my experience, city labels are more useful for orientation and zooming in case of GPS that gives spurious data.

Also, would it be desirable to render labels for tourism=alpine_hut? In my experience it is also useful for orientation.

**Comment by ENT8R** [comment]
Region, county and state labels are very useful, that's right!
And labels for alpine_hut might be useful too, because often there is not that much to display around it, so it is good for orientation.

**Comment by matkoniecz** [comment]
Note that I proposed hiding kind: [region, county, state] (to make more space for city labels), so I guess that this part is rejected.

**Comment by ENT8R** [comment]
Mmhh, then I understood it wrong...
Maybe it is the best to display labels for regions, counties and states only at a low zoom level and then labels for cities at a high zoom level

**Comment by westnordost** [comment]
IMO it should be just what the vector tile server provides, without further refining this, even if it is not 100% perfect.
I don't like at all how the default tangram styles are so over-engineered, ... it's too much maintenance work!

**Comment by ENT8R** [comment]
I agree
