### ISSUE TITLE
Power poles

### ISSUE THREAD

**Issue by ENT8R** [ENT8R/streetcomplete-mapstyle#2]
StreetComplete has a quest for power poles (see [#187](https://github.com/westnordost/StreetComplete/issues/187) and [#493](https://github.com/westnordost/StreetComplete/pull/493)) so it would be useful to have them displayed as a little dot

**Comment by westnordost** [comment]
Hmm, but why? This is a general question: Is the fact that the app asks questions about a type of element a valid reason to have it displayed on the map?

**Comment by ENT8R** [comment]
Mmhh, I think you are right... Otherwise the map will be overloaded with unnecessary information, especially when there is no quest for the element.
