### ISSUE TITLE
drop landuse styling (?)

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/streetcomplete-mapstyle#21]
I am not sure what is the purpose of https://github.com/ENT8R/streetcomplete-mapstyle/blob/master/style.yaml#L69

Effects are quite random as parts of landuse on lower zoom levels is dropped.

It is also not useful as QA displaying areas with missing landuse mapping as natural=* is omitted.

Overall it is quite confusing - but maybe displaying semi-random pattern was the goal?

**Comment by ENT8R** [comment]
> but maybe displaying semi-random pattern was the goal?


Yes, that's right. Otherwise the whole map will be only light green...

**Comment by ENT8R** [comment]
So, can I close this?
