### ISSUE TITLE
Is it planned to change road color in feature?

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/streetcomplete-mapstyle#24]
If not, then I think that 
```
    road_color: '#4da39a'
```

is enough, I see no reason to keep

```
    major_road_color: '#4da39a'
    minor_road_color: '#4da39a'
    highway_color: '#4da39a'
```

Even in case of keeping separate road color variables then probably

```
    major_road_color: global.road_color
    minor_road_color: global.road_color
    highway_color: global.road_color
```

should be used

**Comment by ENT8R** [comment]
As @westnordost said:
> only things need to be shown that matter on the survey (on foot), i.e. colored distinctions between different roads (major, minor,...) are not necessary

So I think it is enough to have one color for all roads
