### ISSUE TITLE
license file is missing

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/streetcomplete-mapstyle#3]
I propose gplv3 to match StreetComplete

**Comment by matkoniecz** [comment]
After adding license I may start making some PRs for accepted issues

**Comment by ENT8R** [comment]
A license is now available!

**Comment by matkoniecz** [comment]
Thanks - now I am waiting for response in other tickets what you think about my suggestions and whatever you would be happy about copying solution from my style.

**Comment by ENT8R** [comment]
Well, I think everything which is tagged with "enhancement" can be implemented.

**Comment by ENT8R** [comment]
And if you want to work on a feature, just write a short message in the issue so I can assign you

**Comment by westnordost** [comment]
Beware of the feature creep though. That's why I asked at the beginning (what are) the valid arguments for adding a feature.
