### ISSUE TITLE
make intendation consistent

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/streetcomplete-mapstyle#33]
Currently global.yaml and base-style.yaml have different space count what makes merging these files for testing rendering overly complicated.

Potential solutions: use tabs, use 2 spaces, use 4 spaces, use N spaces. But it should be the same everywhere.

**Comment by matkoniecz** [comment]
@ENT8R Are you planning on fixing this or waiting for PR? If waiting for PR - do you gave any preference (spaces (how many)?, tabs?)?

**Comment by ENT8R** [comment]
I think tabs are the easiest solution... And if you want to, you can create a PR for that... And if you don't want to fix this, I will do this in the next days...
