### ISSUE TITLE
footway/road through building

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/streetcomplete-mapstyle#34]
Compare Pasaż Bielaka at https://mapzen.com/tangram/play/?#19.50000/50.06070/19.93850 and http://www.openstreetmap.org/#map=19/50.06056/19.93874

![selection_007](https://user-images.githubusercontent.com/899988/32414731-c79118c4-c22d-11e7-90ac-f964bb1eb405.png)
![selection_008](https://user-images.githubusercontent.com/899988/32414733-c7ba1788-c22d-11e7-8e53-74e00f4bb1c7.png)

I am not sure how to fix this assuming that 3D buildings must stay,

**Comment by westnordost** [comment]
Is it possible to make the building half-transparent?

**Comment by westnordost** [comment]
It is, and I did.

**Comment by ENT8R** [comment]
This is now fixed.
Looks pretty cool 👍 :
![tangram- 18 7187 50 0605 19 9386_2018-01-31_20 36 13](https://user-images.githubusercontent.com/25306497/35643390-6bf7f658-06c6-11e8-89c0-8a83c6464dce.png)
