### ISSUE TITLE
Merging into StreetComplete

### ISSUE THREAD

**Issue by westnordost** [ENT8R/streetcomplete-mapstyle#36]
I wonder how we want to go on about this. 

There are a few reasons why we should perhaps drop this repository after initial import.

For dropping this repository:
- tangram-play and scene preview will not work anymore in a few days, so testing needs to be done in StreetComplete anyway
- the style(s) cannot be copied over 1:1. I.e. the URLs of the fonts, style imports  and sdk keys  in this repository need to be changed on (each) import changed. (Though perhaps after Mapzen shutdown, this is no issue anymore because you simply fix the URLs once then)
- if people have feature requests for the map display, they will naturally post it in the StreetComplete project first (and I need to forward them here then)

For keeping this repository:
- You do not have direct push access on changing the stylesheet anymore
- The liability of maintaining this stylesheet shifts from the author (you) more to me because of the above point.
- The satellite style and the dark style can properly maintained, even though I do not plan to put them into the app right now

If we keep this repository, it would maybe make sense to adopt a (crude) versioning, so I know when I should update from here.

**Comment by matkoniecz** [comment]
> tangram-play and scene preview will not work anymore

Is it feasible to run tangram-play locally (either from saved HTML file or some not overcomplicated server on the computer of user)?

**Comment by ENT8R** [comment]
> if people have feature requests for the map display, they will naturally post it in the StreetComplete project first (and I need to forward them here then)

I agree, this can be annoying...

> You do not have direct push access on changing the stylesheet anymore

But I can open a new Pull Request easily 😄 

> The satellite style and the dark style can properly maintained, even though I do not plan to put them into the app right now

Do you plan to not put them into the app because you don't have the time to implement westnordost/StreetComplete#673 or because to keep the app as simple as possible?

> If we keep this repository, it would maybe make sense to adopt a (crude) versioning, so I know when I should update from here.

Maybe we can make it similar to the _old_ cinnabar-style. If you want to, I can also make a new PR everytime there is a new version of this style...

**Comment by westnordost** [comment]
Okay let's leave it as is.

**Comment by ENT8R** [comment]
I just released [v1.0.0](https://github.com/ENT8R/streetcomplete-mapstyle/releases/tag/v1.0.0). Should I notify you if there is a new version of the style in the future or should I simply make a PR?

**Comment by westnordost** [comment]
A PR would be fine
