### ISSUE TITLE
style tuning for SC

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/streetcomplete-mapstyle#39]
For start: map style looks really nice, I really like colour scheme.

As I understand from https://github.com/ENT8R/streetcomplete-mapstyle/issues/34 buildings are supposed to be transparent. At least on my phone buildings are not transparent.

Also tangram-es has some complaints.

```
02-01 00:24:17.098 12380-12380/de.westnordost.streetcomplete.debug D/Tangram: TANGRAM map.cpp:229: Loading scene file: asset:///map_theme/scene.yaml
02-01 00:24:17.104 12380-12380/de.westnordost.streetcomplete.debug D/Tangram: NOTIFY importer.cpp:215: Merging different node types: 'building_color'
                                                                              '#ccd6ee'
                                                                              <==
                                                                              '[0.8, 0.83, 0.93, 0.75]'
02-01 00:24:17.104 12380-12380/de.westnordost.streetcomplete.debug D/Tangram: NOTIFY importer.cpp:215: Merging different node types: 'building_outline_color'
                                                                              '#b9c3d9'
                                                                              <==
                                                                              '[0.73, 0.76, 0.85, 0.75]'
02-01 00:24:17.145 12380-12380/de.westnordost.streetcomplete.debug D/Tangram: WARNING texture.cpp:274: OpenGL ES doesn't support texture repeat wrapping for NPOT textures nor mipmap textures
02-01 00:24:17.145 12380-12380/de.westnordost.streetcomplete.debug D/Tangram: WARNING texture.cpp:275: Falling back to LINEAR Filtering
02-01 00:24:17.155 12380-12380/de.westnordost.streetcomplete.debug D/Tangram: WARNING sceneLoader.cpp:1731: Can't find data source streetcomplete_quests for layer streetcomplete_quests
02-01 00:24:17.155 12380-12380/de.westnordost.streetcomplete.debug D/Tangram: WARNING sceneLoader.cpp:1731: Can't find data source streetcomplete_geometry for layer streetcomplete_geometry
02-01 00:24:17.158 12380-12380/de.westnordost.streetcomplete.debug D/Tangram: WARNING styleParam.cpp:160: Unknown StyleParam dash:1,2,
02-01 00:24:17.163 12380-12380/de.westnordost.streetcomplete.debug D/Tangram: WARNING styleParam.cpp:160: Unknown StyleParam dash:0.6,0.4,
02-01 00:24:17.163 12380-12380/de.westnordost.streetcomplete.debug D/Tangram: WARNING styleParam.cpp:160: Unknown StyleParam dash_background_color:#e0c9b3
02-01 00:24:17.164 12380-12380/de.westnordost.streetcomplete.debug D/Tangram: WARNING sceneLoader.cpp:292: Parsing camera: 'invalid node; this may result from using a map iterator as a sequence iterator, or vice-versa':
                                                                              'fov: 80'
```

**Comment by matkoniecz** [comment]
planned look: https://github.com/ENT8R/streetcomplete-mapstyle/issues/34#issuecomment-362045823

how it looks at least at Xiaomi Redmi 4 with Android 6.0.1 at 52823969

![screenshot_2018-02-01-00-33-08-902_de westnordost streetcomplete debug](https://user-images.githubusercontent.com/899988/35653292-c8335040-06e7-11e8-8e9a-b6a108651986.png)

**Comment by westnordost** [comment]
2 of 3 problems seem to be an issue with tangram-es. One of these, the transparency issue, that is, could be workaround by the style.

**Comment by ENT8R** [comment]
In 4a335ec I fixed all those warnings and notify messages created by tangram-es. Before this commit boundaries were not displayed at all which is pretty strange because in Tangram Play everything worked fine...
I couldn't fix the transparency issue yet... Maybe it has something to do with this:

> **Currently, alpha values are ignored in the `add` and `multiply` `blend` modes, and respected in the `inlay` and `overlay` modes. For more on this, see the [`blend`](https://mapzen.com/documentation/tangram/styles/#blend) entry.

(Source: https://mapzen.com/documentation/tangram/draw/#color)

**Comment by ENT8R** [comment]
That's totally strange:
In Tangram Play everything works fine:
<img src="https://user-images.githubusercontent.com/25306497/35668602-61be77ae-0732-11e8-80bf-290f203a9a81.png" width="500px">
But in StreetComplete using the **exact** same stylesheet, it looks like this:
<img src="https://user-images.githubusercontent.com/25306497/35668695-bfefeb6e-0732-11e8-9cbb-ee81fb14e522.png" width="200px">
I have absolutely no clue why...

**Comment by matkoniecz** [comment]
>  I have absolutely no clue why...

I already encountered similar situations before, typically it is caused by JS rendering and tangram-es rendering interpreting the same code differently or due to missing implementation of some functions (tangram-es is missing some abilities of tangram play).

**Comment by ENT8R** [comment]
It works even with the dark style:
<img src="https://user-images.githubusercontent.com/25306497/35674035-aa84b12c-0743-11e8-8527-a6ac09d35b11.png" width="300px">

**Comment by ENT8R** [comment]
I am closing this now because all issues tangram-es complains about are fixed and I can't find a solution for the building transparency... It seems to be unfixable.
