### ISSUE TITLE
consider showing underground footways

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/streetcomplete-mapstyle#40]
Hiding underground railways and waterways makes sense, but especially in cities underground passages are frequently quite important.

I would reconsider hiding them.

**Comment by ENT8R** [comment]
But this will add a lot of clutter again... Especially if there is another street **above** the underground way... 
And a surveyor won't have a good GPS connection inside of such a passage 😄

**Comment by matkoniecz** [comment]
Maybe it depends on location but it my city clutter would be minimal and ways like this are quite important - like https://www.openstreetmap.org/way/45581610#map=19/50.07115/19.94772

But maybe it generally is a clutter.

**Comment by westnordost** [comment]
I think it would be okay if
1. it is guaranteed that tunnels always render below the other things
2. it does not add an unreasonable amount of style code (I.e. do not duplicate all the drawrules with tunnel=yes)
3. It is drawn half-transparent and/or dashed

**Comment by matkoniecz** [comment]
> it is guaranteed that tunnels always render below the other things

doable with order parameter, but I would render tunnels above water and "any landuse" area.

> it does not add an unreasonable amount of style code

It only requires subrule with filter: {is_tunnel: true} that applies dashing/transparency/whatever

**Comment by HolgerJeromin** [comment]
Good testcase:
In Aachen are some highway tunnel areas mapped (correct imo, as there were even small concerts taking place :-)
https://www.openstreetmap.org/way/17393426
https://www.openstreetmap.org/way/27578466
