### ISSUE TITLE
Show POIs of quests (benches, power poles and fire hydrants)

### ISSUE THREAD

**Issue by rugk** [ENT8R/streetcomplete-mapstyle#41]
Sorry for asking such a dump question, but does it show:

* [x] trams and such lines (great for orientation)
* [ ] benches (this is a potential future quest)

more to come, when I think of more…

**Comment by matkoniecz** [comment]
It is expected to look at already reported issues before opening a new one.

See #5 for start


It is also expected to read at least readme. See https://github.com/ENT8R/streetcomplete-mapstyle/blob/master/README.md#what-should-not-be-added for start.

**Comment by rugk** [comment]
Ups, sorry, created this issue on my phone, so did not look so much into this. So it ma only be about benches, which is - to some extend a POI -, but a possible further quest, i.e. [benches](https://github.com/westnordost/StreetComplete/issues/484).

**Comment by ENT8R** [comment]
Regarding the bench POI:
Take a look at what @westnordost said in https://github.com/ENT8R/streetcomplete-mapstyle/issues/2#issuecomment-340024362
I don't think that we need to add every single POI...

**Comment by rugk** [comment]
No, but at least the ones where quests are in the map… And now we have it merged, so repopening…

**Comment by rugk** [comment]
same with power poles or fire hydrants.

**Comment by rugk** [comment]
Just read your linked comment. So okay, I'd argue otherwise, but I think it is okay…
