### ISSUE TITLE
reduce prminence of minor railways

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/streetcomplete-mapstyle#42]
railways tagged with service tag may be rendered later and/or as less prominent, resulting in less cluttered map (making PR for that is on my TODO list, though given unclear future of vector tiles it is relatively low)

**Comment by ENT8R** [comment]
Do you want this to be included in v4.0 of SC?

**Comment by westnordost** [comment]
It's not a must

Am 20. Februar 2018 16:44:18 MEZ schrieb ENT8R <notifications@github.com>:
>Do you want this to be included in v4.0 of SC?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ENT8R/streetcomplete-mapstyle/issues/42#issuecomment-367019217

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by ENT8R** [comment]
I just fixed it right now
