### ISSUE TITLE
Add rendering of turn lanes

### ISSUE THREAD

**Issue by RubenKelevra** [ENT8R/streetcomplete-mapstyle#43]
Since we're already on a survey, a rendering of turn lanes, at a very high zoom level would be great. So we can check them for bugs as well and file those as OSM notes on the go.

To be clear, I don't ask for a mapping feature for turn lanes here, which would be too much of a hassle I suppose.

A typical view at a zoom-level where turn lanes rendering would be great:

![screenshot_20180208-095715](https://user-images.githubusercontent.com/614929/35964226-5bb41456-0cb7-11e8-8da2-cb636b6be40e.jpg)

**Comment by ENT8R** [comment]
I'm sorry, but I don't really get your point... Turn lanes should be displayed already... Do you want them to be a little bit smaller?

**Comment by ENT8R** [comment]
Or do you mean the arrows displayed on the road?

**Comment by westnordost** [comment]
I think the latter is actually not possible with tangram, ... at least, noone has tried.

**Comment by ENT8R** [comment]
So @RubenKelevra what do you want to do? I don't really get your point... The roads are displayed... So what is the "issue"?

**Comment by RubenKelevra** [comment]
Well, the screenshot shows a junction which has different ways for each lane, which is basically a big mess when rendered, newly design junctions have often a tag turn:lanes[1] which give the ability to assign specific lanes to specific destinations. But mapping them from satellite images is often not possible, so a survey is needed.

I know this ticket is waaay out of the scope of everything currently possible, but maybe keep this in a backlog area until we get a split-way function? :)

[1] https://wiki.openstreetmap.org/wiki/DE:Key:turn:lanes

**Comment by ENT8R** [comment]
Could you maybe provide a link to the specific location?

**Comment by ENT8R** [comment]
Mmhh... I still have no clue how you want it to be displayed... Should be big street be split up into two separate streets, one for turning left and the other one for turning right?

**Comment by RubenKelevra** [comment]
Sure, here's a way which is tagged with lane-tags:

https://www.openstreetmap.org/way/82652409

And this is how JOSM would render the lanes, if lane-rendering style is activated:
![bildschirmfoto von 2018-02-23 19-45-13](https://user-images.githubusercontent.com/614929/36610938-2b250f12-18d2-11e8-95b4-1d4f0a3229a7.png)

**Comment by RubenKelevra** [comment]
And this is the same area in SC

![screenshot_20180223-195352](https://user-images.githubusercontent.com/614929/36611418-a3e535ac-18d3-11e8-83d2-27e5df7ce38c.jpg)

**Comment by ENT8R** [comment]
So you want arrows for each direction displayed on top of the road?
This is not possible at all... (https://github.com/tilezen/vector-datasource does not support `turn:lanes`)

**Comment by RubenKelevra** [comment]
Ah, sad ... okay, I think pulling those pieces of information live from the database is too much hassle.

**Comment by ENT8R** [comment]
> I think pulling those pieces of information live from the database is too much hassle.

Yeah, and not every user has always an internet connection...

Maybe Vespucci is the right choice for you if you want to map those things while you are on survey...
