### ISSUE TITLE
Render bridges of streets over each other

### ISSUE THREAD

**Issue by Akasch** [ENT8R/streetcomplete-mapstyle#44]
While browsing the map I have noticed that it is not possible in the current style to see that one could not go from one street to the other as there is a bridge. The Issue can be seen here:

Streetcomplete-Style: https://map-data.de/#map=19/53.63997/10.00312&style=streetcomplete-light
Openstreetmaps: https://www.openstreetmap.org/#map=19/53.63997/10.00312

On a side note: The I think the gates would be a good addition to, as one can't go into the airfield.

Or a little to the east:
https://map-data.de/#map=19/53.63790/10.00908&style=streetcomplete-light
https://www.openstreetmap.org/#map=19/53.63790/10.00908

**Comment by rugk** [comment]
Ah that map data link is nice, how did you get it? In the Readme I can only see Tangram Play links.

**Comment by Akasch** [comment]
@rugk it is my domain (mostly for serving the vector tiles at the moment) and I wanted to play around a little bit, so it is a work in progress, you can see the ugly code over at https://github.com/Map-Data/map-data.de

**Comment by rugk** [comment]
Indeed would be good to find an alternative, especially as Tangram Play does not work anymore (because of the MapZen shutdown).

**Comment by ENT8R** [comment]
Tangram Play **does** work here: https://tangram.city/play/

**Comment by rugk** [comment]
Ah, okay so it is just your Readme link. Always shows "Request error with a status of Not Found".

**Comment by ENT8R** [comment]
Yeah, because it links to the local files...
Just replace the import statement with the following:
```yaml
import:
    - https://raw.githubusercontent.com/ENT8R/streetcomplete-mapstyle/master/global.yaml
    - https://raw.githubusercontent.com/ENT8R/streetcomplete-mapstyle/master/layers/land.yaml
    - https://raw.githubusercontent.com/ENT8R/streetcomplete-mapstyle/master/layers/labels.yaml
    - https://raw.githubusercontent.com/ENT8R/streetcomplete-mapstyle/master/layers/roads.yaml
```

**Comment by ENT8R** [comment]
I changed the URLs in the Readme and now it should work as expected... I only need to replace them with the commented section each time I open a PR to update the mapstyle in the app

**Comment by ENT8R** [comment]
Regarding this issue: I think it might be related to #9...

**Comment by westnordost** [comment]
> I changed the URLs in the Readme and now it should work as expected... I only need to replace them with the commented section each time I open a PR to update the mapstyle in the app

Or, you can have two branches and sync them before each PR.

**Comment by westnordost** [comment]
Regarding this feature request: This would definitely be nice, but I do not really know how this can be solved (without introducing a lot of style code).
One would think that the `feature.sort_rank` would take care of this (plus tunnels).

**Comment by ENT8R** [comment]
Adding
```yaml
bridges:
  filter:
    - is_bridge: true
  draw:
    lines:
      outline:
        cap: butt
        order: 400
```
to the default `road-outline` works quite well:
<img src="https://user-images.githubusercontent.com/25306497/36063778-a93ee392-0e81-11e8-9f8b-c556a0486881.png" width="300px">

**Comment by ENT8R** [comment]
The solution 🔝 works in all cases I've seen so far... If you are seeing a wrong rendered bridge, just tell me here!

**Comment by HolgerJeromin** [comment]
I think multiple crossing bridges with layer 1 and 2 would not work. But they are rare and no special handling needed.
