### ISSUE TITLE
colored distinctions between different roads

### ISSUE THREAD

**Issue by rugk** [ENT8R/streetcomplete-mapstyle#45]
This has been requested in the original issue https://github.com/westnordost/StreetComplete/issues/183#issuecomment-299334841: 
> only things need to be shown that matter on the survey (on foot), i.e. colored distinctions between different roads (major, minor,...) are not necessary

So maybe make it visible whether a street is for cyclists, for cars or for pedestrians. Currently they are all white…

**Comment by ENT8R** [comment]
> i.e. colored distinctions between different roads (major, minor,...) are **not** necessary

@westnordost said that they are **not** necessary...

And do you think that this is useful information for survey by foot?

**Comment by rugk** [comment]
Uuups, I should read what I quote…  😆 

I was just surprised that e.g. even autobahns are in the same color as other streets.
So, I guess, it may help, because you also need some basic navigation in StreetComplete to see where you are going, I mean I don't always want to switch between two apps and carrying two phones is also not really comfortable.
To exaggerate: You would not want to walk on a autobahn… 😉 

So to some extend this is similar to https://github.com/ENT8R/streetcomplete-mapstyle/issues/44. Seeing bridges correctly is not necessary for solving quests, but it's good for navigation to see where you cannot go. Also to some extend this would be a safety feature, to notice that this is a big street in front of you.

**Comment by westnordost** [comment]
KISS

**Comment by ENT8R** [comment]
> Also to some extend this would be a safety feature, to notice that this is a big street in front of you.

But bigger streets are rendered bigger too... I don't think that it is needed to differenciate between the different roads by giving them a different color...
And as @westnordost said: Keep it simple 😉 
So I am closing this for now...
