### ISSUE TITLE
Tunnels not being rendered and swimming pools look weird 

### ISSUE THREAD

**Issue by iamnunocaldeira** [ENT8R/streetcomplete-mapstyle#46]
![screenshot_20180210-180707](https://user-images.githubusercontent.com/15980854/36065077-77ba75dc-0e8d-11e8-931e-f542e66a2bab.png)
![screenshot_20180210-180722](https://user-images.githubusercontent.com/15980854/36065080-7e2bf6b6-0e8d-11e8-806c-d0900c9910e4.png)

Here's examples

**Comment by ENT8R** [comment]
Could you maybe also post a direct link to the area you are referring to?

**Comment by iamnunocaldeira** [comment]
https://osmand.net/go?lat=32.662186&lon=-16.897638&z=15

The pools there's plenty of houses with them nearby the sea, head south from that link

**Comment by ENT8R** [comment]
Thank you!
I think that the pools are displayed weirdly because they are a little bit too small...
I will try to fix this!

**Comment by ENT8R** [comment]
Looks better now!

**Comment by westnordost** [comment]
I think the pool problem will not be fixable. I looked into that myself. To fix this, basically, one would need to remove that nice coastline effect - nah, better slightly weird-looking pools then!

**Comment by ENT8R** [comment]
I just made the width of the effect for swimming pools at a high zoom level a little bit smaller and it looks better than before...

**Comment by westnordost** [comment]
You mean low zoom levels, right?

**Comment by ENT8R** [comment]
On zoom levels **higher** than 18...

**Comment by matkoniecz** [comment]
> I think the pool problem will not be fixable. I looked into that myself. To fix this, basically, one would need to remove that nice coastline effect - nah, better slightly weird-looking pools then!

What about keeping coastline effect for features larger than some minimal size? From what I see it is causing problems for small water areas?

I think that filters similar to one that I use to display water names would fit - https://github.com/matkoniecz/Zazolc/blob/fork/app/src/main/assets/map_theme/fork-style.yaml#L470

**Comment by ENT8R** [comment]
Might be possible because swimming pools won't have waves if you don't jump into it... 😄

**Comment by goldfndr** [comment]
https://github.com/datadesk/web-map-maker/blob/master/map-styles.yaml filters out swimming_pool then has a separate rendering just for swimming_pools.

**Comment by iamnunocaldeira** [comment]
Since this was reopened, here's another one. Port areas/facilities are being displayed as green, which confuses. A gray colour or light orange would be better.

**Comment by iamnunocaldeira** [comment]
![screenshot_20180312-215915](https://user-images.githubusercontent.com/15980854/37311950-1edb7b20-2641-11e8-9c19-bf1783d814c3.png)
Port area screenshot, which you can see it confuses with nearby parks.

**Comment by matkoniecz** [comment]
> Since this was reopened, here's another one.

Please, open new issues for new issues if problem is not reported. Also - this one is reported as #57

**Comment by ENT8R** [comment]
The tunnel problem is now tracked in #55
