### ISSUE TITLE
SC release

### ISSUE THREAD

**Issue by westnordost** [ENT8R/streetcomplete-mapstyle#51]
I am aiming to release v4.0 on Wednesday. Are you able to finish the open issues (and create a PR) until then?

**Comment by ENT8R** [comment]
I can try to give my best! I will tell you this evening.

**Comment by ENT8R** [comment]
I am trying to fixing the step issue (#49) right now. But I am not sure if I can fix #48...

**Comment by ENT8R** [comment]
So #49 is fixed but #48 not yet...

**Comment by ENT8R** [comment]
PR was merged, so I am closing this.
