### ISSUE TITLE
area=yes, highway=pedestrian not rendered

### ISSUE THREAD

**Issue by HolgerJeromin** [ENT8R/streetcomplete-mapstyle#52]
https://www.openstreetmap.org/way/24481436
Is not rendered.

**Comment by ENT8R** [comment]
What colour would you propose for squares like this? Maybe `#e0e0e0`
![#e0e0e0](https://placehold.it/50/e0e0e0/000000?text=+)

**Comment by HolgerJeromin** [comment]
Would expect the same as street color

**Comment by ENT8R** [comment]
Well, that's just white and a little bit boring (especially for big squares), isn't it?

**Comment by HolgerJeromin** [comment]
areas are not more important than streets imo

**Comment by ENT8R** [comment]
But for the simplicity of the map, I'd say we should leave it out, or at least filter it by area... Maybe 1000m² is a good value?

**Comment by HolgerJeromin** [comment]
The area has an active quest. It is extrem confusing to have an street quest without seeing one

**Comment by ENT8R** [comment]
Well, that's true...

**Comment by westnordost** [comment]
Pedestrian areas, independent of the size, should just have the same fill and border color and width as streets

Am 20. Februar 2018 17:38:51 MEZ schrieb ENT8R <notifications@github.com>:
>Well, that's true...
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ENT8R/streetcomplete-mapstyle/issues/52#issuecomment-367037747

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
Actually, any street-area. (also saw highway=residential with area=yes and the like)

Am 20. Februar 2018 17:38:51 MEZ schrieb ENT8R <notifications@github.com>:
>Well, that's true...
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ENT8R/streetcomplete-mapstyle/issues/52#issuecomment-367037747

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by ENT8R** [comment]
> also saw highway=residential with area=yes and the like

I don't think that this is supported by https://github.com/tilezen/vector-datasource

**Comment by ENT8R** [comment]
I added rendering for pedestrian squares now. Could you take a look (either at the map or the code) and tell me if this is what you meant?

**Comment by ENT8R** [comment]
IMO, only white looks pretty weird to my eyes... 😉 Nearly all cities I've viewed so far are now completely white (especially the centre of the cities with all its pedestrian streets and area...

**Comment by westnordost** [comment]
Pedestrians streets seem to be rendered the same as footways as they have a slightly different border color. So, squares should probably have that border color than the footways. Also, looking at Münsterplatz in Bonn, it should probably be rendered on top of streets.

**Comment by ENT8R** [comment]
Is it okay now? For me it is still too much white 😄
