### ISSUE TITLE
Buldings below streets are rendered above them

### ISSUE THREAD

**Issue by RubenKelevra** [ENT8R/streetcomplete-mapstyle#54]
I know this is really minor, but I just wanted to just set this on the task-list.

Buildings with a lower level than streets should not be rendered above streets and sub-zero layer buildings maybe should be rendered at a higher opaque level? :)

Example data:

https://www.openstreetmap.org/way/82652409

![screenshot_20180223-201059](https://user-images.githubusercontent.com/614929/36618538-d6d8d28a-18eb-11e8-91a7-b84b948456a4.jpg)

**Comment by ENT8R** [comment]
I wonder why this isn't excluded with `location: underground`...
https://github.com/ENT8R/streetcomplete-mapstyle/blob/e96643a6b8900c6f6ffe73ef28b1bfadc65740ac/layers/land.yaml#L60

**Comment by matkoniecz** [comment]
https://www.openstreetmap.org/way/378955812#map=19/52.51560/13.41816 is not tagged with location=underground, it is a OSM data issue (if that object is really underground) or invalid issue (if that object is not underground)

**Comment by ENT8R** [comment]
It is underground:
![thumb-2048](https://user-images.githubusercontent.com/25306497/36630634-1f85e490-196a-11e8-81c5-2c5c6ffc6150.jpg)
Otherwise it would be on top of this crossing...

**Comment by ENT8R** [comment]
So it is an OSM issue... Should I add `location=underground`?

**Comment by matkoniecz** [comment]
> So it is an OSM issue... Should I add location=underground?

Yes, and yes. I already made "add location=underground" edit for building, if you want you may do the same for other objects there.

@RubenKelevra Note that SC map will update once (a) server serving tiles will process my edit (b) your app cache will flush current data and download new one. (a) part may happen far in future, immediately or not at all.

**Comment by RubenKelevra** [comment]
Thank for the clearification & the fast fix of OSM data... but still, a thing with layer=-2 should be rendered below something without layer-tag - where we assume layer=0 like streets, right?

**Comment by ENT8R** [comment]
This is already done by the tile server...

**Comment by ENT8R** [comment]
Buildings are normally rendered above streets.
