### ISSUE TITLE
tunnel=yes streets (highways) not rendered

### ISSUE THREAD

**Issue by rugk** [ENT8R/streetcomplete-mapstyle#55]
`tunnel=yes` streets (`highway=tertiary`) are not rendered at all. Or they are very small and do not fit to the size of the street.

**Comment by ENT8R** [comment]
Yes, this needs some adjustment (see #48 and maybe also #46)...

**Comment by rugk** [comment]
Is not this rather a bug than an enhancement? I mean a street ending somewhere out of nowhere and beginning some meters away is a strange thing to see on a map.

In the end, it would already help much if the tunnels were being rendered the same as streets. It does not really matter that they are tunnels… But if you want, you could of course at least change the color or so, somehow.
