### ISSUE TITLE
Hard to perceive sport pitches or sport centers

### ISSUE THREAD

**Issue by exploide** [ENT8R/streetcomplete-mapstyle#56]
There are quests concerning pitches or sport centers, e.g. asking which sport is played here or what are the opening hours. But in several situations it is comparably hard to perceive them on the map, which makes them hard to identify in reality and hinders the orientation of the mapper.

This is because they are colored green (which is reasonable), but urban ground as well as grass is also green. Maybe consider some ground related changes to make pitches better perceivable?!

**Comment by matkoniecz** [comment]
Can you give an example? In my experience area rendering by quest itself is good enough to identify a pitch.

**Comment by exploide** [comment]
You are right that the area rendering by the quest is good and really improves the situation. But for identifying one of several pitches while walking nearby w/o having the quest already open, it can still be hard. Additionally it is suboptimal for the personal orientation.

Screenshot 1: The area marked with X contains an open air sports center. Nearly invisible. Especially the different pitches there. (No quest icons since I already solved) Belongs to node https://www.openstreetmap.org/way/24447966
![screenshot_20180307-135019](https://user-images.githubusercontent.com/5670236/37093467-b51031a2-220f-11e8-83d8-1f4f6c038cca.png)

Screenshot 2: Pitches which are a bit better distinguishable but still look like the urban ground near the streets. Belongs to https://www.openstreetmap.org/way/28367203
![screenshot_20180307-135034](https://user-images.githubusercontent.com/5670236/37093535-f170a3a2-220f-11e8-96b1-98e8d16eeb00.png)

Compared to OSM-Carto or the old SC style the visibility is not as good.

**Comment by rugk** [comment]
So you want to change the color of them?
Fair enough, but I can always identify them when I select them and they are highlighted in blue.

**Comment by exploide** [comment]
Yes, @matkoniecz already pointed that out, and I agree. But I think it feels odd if there is something that is not really perceivable on the map but suddenly becomes an outline when opening the quest. I know that the SC style is intentionally simple, but these things help in identifying places and the overall orientation.

Changing colors would be a solution. Maybe making use of multiple shades of green for different things. To be honest I don't know why urban ground is green at all. I know it was originally inspired by Pokémon Go but then at least multiple shades of green?

Or if you all find this good enough, leave it as is. :wink: But in my opinion it could be better.

**Comment by westnordost** [comment]
I find it good enough for now. Perhaps at some later time, more than just 2 colors could be introduced into the simple map style.

**Comment by ENT8R** [comment]
I agree with @westnordost: if the change the colors or introduce even more, new colors, this should be done at once and not over time. So @exploide can this issue be closed then?

**Comment by exploide** [comment]
Ok, I will open a new issue but initially it won't be as complete and constructive as you which, because I simply don't know yet what landuses and landcovers there are and if they are sufficiently visible on the map or not. I also never mapped such things before so I have not much experience with this.

**Comment by ENT8R** [comment]
That's alright! We can add more values over time. This issue should then just be a place for collecting ideas.
