### ISSUE TITLE
Consider introducing more colors

### ISSUE THREAD

**Issue by exploide** [ENT8R/streetcomplete-mapstyle#57]
As a follow up to #56:

It might be beneficial to introduce one or more additional colors to the map style, since some landuses and landcovers are currently not clearly distinguishable, which hinders identification and overall orientation. Probably it's not reasonable to distinguish each and every thing out there, but at least areas of a specific meaning that might be related to asked quests.

* `leisure=pitch` and `leisure=sports_centre` are not very perceivable. See #56 for example. Maybe this depends on the rendering of `landuse=recreation_ground`. I could imagine using different shades of green here.

**Comment by matkoniecz** [comment]
Probably it should be subset of https://wiki.openstreetmap.org/wiki/Standard_tile_layer/Key#Areas

**Comment by mds08011** [comment]
I agree.  I just ran into a case in which an adjacent park, school, and commercial land use were all represented by the same shade of green.  I have attached two screenshots: the 1st is StreetComplete, and the 2nd is the Standard OSM tile (Mapnik?).  On the StreetComplete image, I roughly circled the park.  It really blends into the school to the left, and commercial area across the street to the right.

![StreetComplete](https://user-images.githubusercontent.com/8010709/44622584-00525780-a870-11e8-9139-7e879443f05c.jpg)

![OSM Standard/Mapnik](https://user-images.githubusercontent.com/8010709/44622583-00525780-a870-11e8-8df1-e6daf4c8d3f5.PNG)

https://www.openstreetmap.org/#map=18/32.75658/-117.14724

**Comment by westnordost** [comment]
But why would you want to see that detail on the map in the StreetComplete app?

**Comment by westnordost** [comment]
Your example is a good example of how simplistic this style is, by the way, because on mapnik, you can see a school, a pitch, a playground, a religious landuse, commercial area, residential area and parking lot, all next to each other :-o

**Comment by mds08011** [comment]
I suppose I don't actually need it for StreetComplete directly, but it's just nice to see the distinctions between larger-scale elements like land uses.  If anything, I would prefer land uses not be shown at all compared to being rendered the same color.  When looking at my example, I mentally think "something is wrong", whereas if everything was represented the same as areas without any land use assigned (the tan color), I wouldn't notice.

StreetComplete is my main OSM surveying app, so independent of the quests, I often leave notes to myself to add/correct things on my computer later.  Having a visually representative StreetComplete map allows me to notice more while I am walking around.  However, I also understand that compromises need to be made.  It is not feasible for StreetComplete to show every last way/node/relation.  But given that land-uses are already being shown it seems reasonable to segregate the most common ones into different colors.

**Comment by matkoniecz** [comment]
Main problem is that making "distinctions between larger-scale elements like land uses" in way that is acceptable takes a very significant effort.

**Comment by mds08011** [comment]
I see.  And I am not a developer so take everything I say with a grain of salt.

I was envisioning selecting some of the more common land uses (not everything) and copying the colors of an existing style (like Mapnik).  But I have no idea what the actual sale of effort is.  I opened Tangram Play and saw `landuse_color: '#c6ddaa'` but I wasn't sure how involved it is to add sub-categories.

**Comment by matkoniecz** [comment]
I am still dubious about effort vs values, especially as this map style is intended solely for orientation and current data source suffers from being based on highly outdated OSM data.

------

I thought about having two landuses colors - one for natural areas and vegetation (forest, park, field) and one for man made (residential, parkings, universities, commercial areas etc).

It is a bit confusing to see parking or university area as green on a map and some users consider it as indication that area is unmapped and open notes.

But I am still a bit dubious is it worth doing this. Also what should be done with natural bare areas? Rendering rocks, sand etc as green would be a bit weird.

Maybe vegetation areas vs areas without vegetation rather natural vs man made?

> saw landuse_color: '#c6ddaa' but I wasn't sure how involved it is to add sub-categories.

Adding colors is relatively easy. Tricky part is differentiating many different uses and states of land with colors in way that keeps map readable (based on my experience with https://github.com/gravitystorm/openstreetmap-carto/)

**Comment by westnordost** [comment]
I think adding another color for "green" areas (natural landuses, forests, sports areas, parks,...) is not something that will confuse users. Actually, as @exploide, @mds08011 mentioned, quite the contrary. It is also not that much work to implement, as long as it stays to be a very rough differentiation.

The reason why this is not implemented yet is not because (we) doubt it should be included at all, but because noone thought this important enough to give it a try to see how it looks.

**Comment by westnordost** [comment]
So, anyone wanting to experiment with it, @exploide , @mds08011 ?

**Comment by mds08011** [comment]
I was messing around with Tangram for a while but then got distracted.  I do hope to try again but don't know how soon that will be.
