### ISSUE TITLE
Mapbox / other styles as branches, not as subdirectories

### ISSUE THREAD

**Issue by westnordost** [ENT8R/streetcomplete-mapstyle#62]
I have a suggestion: If you adapt the stylesheet for different tileservers, make branches instead of subdirectories. This makes it much easier to keep them up-to-date and ... well, and so on, I don't need to explain to another developer on GitHub the virtues of version control systems ;-)

Brotip: If one branch beomes more important than the current stylesheet (mapzen) you can make that into the new master and have a branch for the mapzen-stylesheet.

**Comment by ENT8R** [comment]
Oh yes, I will do this as soon as possible!
Thank you for the hint

**Comment by ENT8R** [comment]
Fixed this now. I also improved the website https://ent8r.github.io/streetcomplete-mapstyle/ a little bit so one can select the different styles....

**Comment by westnordost** [comment]
Cool!

There is no building height information for mapbox-like vector tiles?

**Comment by ENT8R** [comment]
According to https://www.mapbox.com/vector-tiles/mapbox-streets-v7/#building

> The **`height`** field contains the height of a building or building part in meters (rounded to the nearest integer). In many cases this value is derived from the `building:levels` tag on OpenStreetMap - we estimate 3 meters per level if no exact height is specified.

**Comment by rugk** [comment]
Uhh, but in this 3d view the streets "go through" buildings and such stuff…

![image](https://user-images.githubusercontent.com/11966684/43968984-0a94ba56-9cc9-11e8-93b1-aa69b2205f83.png)

(only in Mapbox, in Mapzen they are behind the buildings as expected.)

**Comment by ENT8R** [comment]
Yes, I know, the Mapbox style has some issues which are not resolved yet. One big problem is that Mapzen delivers the order of the display with `feature.sort_rank` but Mapbox does not have an equivalent value.
