### ISSUE TITLE
Show mini roundabouts, turning loops and turning circles on the map

### ISSUE THREAD

**Issue by westnordost** [ENT8R/streetcomplete-mapstyle#66]
This information is now available in the vector tile source.

This is a follow-up of #64

**Comment by matkoniecz** [comment]
> roundabouts

I am a bit confused here - roundabouts are already displayed as roads and mini roundabouts seems something to minor to display (unlike all other POIs)

**Comment by westnordost** [comment]
Mini roundabouts are about as big as a turning circle.

**Comment by westnordost** [comment]
It's rendered now, alas not the way it would look natural but just as a red dot, because tangram-es is unable to render points with the blend mode `inlay` ( https://github.com/tangrams/tangram-es/issues/595 )
