### ISSUE TITLE
Night mode looks futuristic due to it's transparent elements

### ISSUE THREAD

**Issue by rugk** [ENT8R/streetcomplete-mapstyle#67]
Futuristic… or retro… or something like that…

in any case in real life buildings are not transparent, not even in the night.

This is how it looks:

![image](https://user-images.githubusercontent.com/11966684/50562857-23a67b00-0d18-11e9-825b-698b45730661.png)

https://tangram.city/play/?scene=https://raw.githubusercontent.com/ENT8R/streetcomplete-mapstyle/master/streetcomplete-dark-style.yaml#16.71528/52.52045/13.40732

So especially when there are buildings "on top of each other" they look different and the orange seems to glow and highlight them. I guess we do not need such a futuristic view…

**Comment by westnordost** [comment]
So, real buildings are actually blue then?

**Comment by rugk** [comment]
Well… they certainly do not have to look like [in tron](https://en.wikipedia.org/wiki/Tron)… :wink: 

So glass houses that sometimes even layer on top, look really nice, but not really serious… I could also think this "hard graphics" stress the battery of the mobile phone.

**Comment by westnordost** [comment]
Ah this is solved as well
