### ISSUE TITLE
Show parking lots as landuses (green)

### ISSUE THREAD

**Issue by westnordost** [ENT8R/streetcomplete-mapstyle#68]
(moved from https://github.com/westnordost/StreetComplete/issues/1308 )

**Comment by matkoniecz** [comment]
In general, showing amenities as green would be a good idea. Some mappers interpret missing green as that nothing is mapped there resulting in confusing notes like "here is university XYZ" where such entity is mapped.

**Comment by matkoniecz** [comment]
According to my test parkings are currently shown in green.

So either it got fixed in meantime or original report was based on an assumption that brown area is special.
