### ISSUE TITLE
Show house numbers for related quest

### ISSUE THREAD

**Issue by laurentS** [ENT8R/streetcomplete-mapstyle#70]
I love the app, I'm impressed by the ease of use, but I've found it difficult to use for quests around terraced houses in the UK (and I suspect it applies elsewhere).

When adding house numbers in a long street of fairly small houses, all buildings on the map start to look the same, and with a somewhat low GPS accuracy between buildings, it is easy to lose track of which house number goes where.

I feel that it would help a lot if they were shown on the map, or at least could be toggled on when collecting house numbers (and building types as well, for the same reason). I don't know if it's possible with the use of tangram though...

**Comment by westnordost** [comment]
Actually, the house numbers, as well as the street names, are already shown on the map. Perhaps you need to zoom in more?

**Comment by matkoniecz** [comment]
Is it possible that house numbers were recently added?

It is possible that it is a case of "Maps no longer updating on new vector tile server, out-of-date with quests" - https://github.com/westnordost/StreetComplete/issues/1011

**Comment by laurentS** [comment]
@westnordost indeed! I explored a bit further, and you're right, they are there. So I guess @matkoniecz is right. I added house numbers in the past few weeks, probably a few hundreds, so maybe it is a matter of tiles not updated.

I guess I'll close this, sorry for the noise.
