### ISSUE TITLE
Use better satellite map

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/streetcomplete-mapstyle#72]
Current Mapbox satellite map is not working and returns that access is not authorised.

In addition, in general Mapbox-hosted data requires to have Mapbox spying enabled (based on memory, I failed to find usage rules).

I have working version of Esri aerial (I still need to check licence but it is in JOSM as one of layers so should be OK) and it actually works.

Bing aerial is generally better quality than Esri but I failed to get it working (I need tile URL pattern and I failed to locate it, JOSM listing in aerial list suggests that they have their own special addressing method).

I plan on making Esri PR as the first step and later will again try to figure out Bing.

**Comment by ENT8R** [comment]
From reading https://wiki.openstreetmap.org/wiki/Esri#Interested_in_using_Esri_World_Imagery_in_your_own_application.3F one can use Esri Satellite Imagery if
> 1. You have signed up for a free ArcGIS Developer account
> 2. You are not generating revenue from your app (in the form of advertisements or subscriptions)
> 3. Your users request < 1 million tiles/month
> 4. You properly attribute both Esri and all of our data providers (reference: https://github.com/esri/esri-leaflet#terms)

Point 2 and 3 should be no problem, 4 needs to be added in the application which uses the layer (StreetComplete) but why do you have to create a developer account if there is no real access restriction to use the imagery?

They also say
> Our announcement pertains specifically to non-revenue generating applications that are entirely centered around editing OpenStreetMap.

...which is certainly the case for StreetComplete

**Comment by matkoniecz** [comment]
> why do you have to create a developer account if there is no real access restriction to use the imagery?

You agree to ToS during creating it? You become more likely to use their paid products? Was added by accident?

**Comment by westnordost** [comment]
I created an account at esri, and created a new application "StreetComplete" there. Then, I could select which service I'd like to use...
![image](https://user-images.githubusercontent.com/4661658/63463202-fbad8880-c45c-11e9-8387-3157e36f9329.png)
...but the Satellite imagery doesn't even turn up there. So what gives, I guess we can ignore point 1.
