### ISSUE TITLE
who is author of fonts from fonts folder

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/streetcomplete-mapstyle#74]
Sorry for bothering about this issue - but do you remember what was source of https://github.com/ENT8R/streetcomplete-mapstyle/tree/master/fonts folder? There is an Apache licence there, but it seems that authors of fonts are not specified anywhere.

**Comment by ENT8R** [comment]
I took it from https://fonts.google.com/specimen/Montserrat but it can also be found at the official repository of the Montserrat font: https://github.com/JulietaUla/Montserrat
I actually don't really know why there is an Apache license in the folder, the correct license should be the SIL Open Font License. I changed that now.

**Comment by ENT8R** [comment]
Actually it might be that I took the files from https://github.com/tangrams/cinnabar-style/tree/gh-pages/fonts (the style that StreetComplete used before this style), this would also explain where the Apache license came from, as I simply copy-and-pasted the files...

**Comment by matkoniecz** [comment]
Thanks!
