### ISSUE TITLE
reconsider colour palette

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/streetcomplete-mapstyle#8]
Maybe it is just me but this colour scheme is really straining my eyes.

Note: feel free to close and reject especially this one, it is impossible to please everybody. It is intended merely as feedback. Maybe I am an outlier.

**Comment by westnordost** [comment]
I understand this was an experiment first to copy a more playful look. As long as the colors are defined in variables, as @ENT8R did, it is easy to change them.

**Comment by matkoniecz** [comment]
Personally I am quite happy about my style (whiteish background, green parks/forests, purple roads), but I am unsure is it something that would be considered as nice-looking by others.

My style may be viewed at https://mapzen.com/tangram/view/?api=53844/1164#17.19025/50.07410/19.93505 (slightly simplified version of https://github.com/matkoniecz/Zazolc/blob/fork/app/src/main/assets/my-style.yaml )

**Comment by ENT8R** [comment]
I think we should definitely change the road color because it  is quite hard to distinguish between roads and rivers

**Comment by rugk** [comment]
I thin the day map is really too green. The dark map looks quite good, especially when you uncomment the "base import" it looks good.

**Comment by ENT8R** [comment]
What do you mean with "uncommenting the base import?"

**Comment by rugk** [comment]
There is an `# import base-style` or something like that (in the playground). I just removed the comment symbol there.

**Comment by ENT8R** [comment]
Mmhh... I thought this won't work because the file is not stored on the servers of mapzen... So I imported it through the whole URL of the raw file which is stored on github... But actually, this does not matter at all...

**Comment by westnordost** [comment]
Check out my fork. Perhaps you want to merge my changes to origin?

**Comment by westnordost** [comment]
![screenshot1](https://user-images.githubusercontent.com/4661658/35360157-0a0e3c04-015d-11e8-994e-60b3c458a1ef.png)

**Comment by rugk** [comment]
Hmm I think it is very blue and thanks to this green grassland there not really comfortable on my eyes. (A less "blueish" green would be better.)

Compared with the default (current) mapstyle I also think the shadow on the "walls" is a bit strong and I miss some contours in general (e.g. the big streets had some red contours in the default mapstyle).

**Comment by rugk** [comment]
Or wait, this green is not grassland? Right? if so, you should not color it green.... To be honest, in the current state I'd still like the default mapstyle better.

**Comment by westnordost** [comment]
*Any* landuse has the same color. It's not supposed to represent the specific feauture but is a background color.

**Comment by rugk** [comment]
Aha ok, but in the usual Mapzen style I see grassland areas are green and this really helps for orientation.

**Comment by ENT8R** [comment]
IMO your colors are a little bit hard to distinguish and they look a little bit too _pale_ for me... But sure, you are the maintainer of SC and should have the control over the colors, we can not fulfill every wish of every single user...

**Comment by westnordost** [comment]
![screenshot2](https://user-images.githubusercontent.com/4661658/35487805-ffcc9c38-047f-11e8-8c19-88d9aaa1a990.png)

**Comment by matkoniecz** [comment]
I really like this colour scheme. Though I am curious - is man_made=bridge displayed like building or is it a bridge mistagged as building?

**Comment by westnordost** [comment]
What bridge? Bridges are green.

**Comment by westnordost** [comment]
![screenshot3](https://user-images.githubusercontent.com/4661658/35488298-88ad7756-0486-11e8-9681-22daad3c08af.png)

Still fiddling around with this. Perhaps I can copy&paste some shaders from tron

**Comment by ENT8R** [comment]
Wow! Great! It looks awesome! I will merge your PR now. Thank you for the good work 👍

**Comment by ENT8R** [comment]
Is this issue fixed now or are there still further improvements/wishes?

**Comment by rugk** [comment]
But the last thing is the night mode, right?

(Otherwise I really don't see a need to make rivers black... uhh looks poisonous)

https://github.com/ENT8R/streetcomplete-mapstyle/issues/8#issuecomment-361100538 looks good, IMHO, from the colours. But are these bridges green because they are bridges or because there is grass?
In any case, I'd say you should not use green to indicate something else than grass or some other natural things.

BTW a "tryout" link would be nice to see it in action...

**Comment by ENT8R** [comment]
> BTW a "tryout" link would be nice to see it in action...

* [Normal](https://mapzen.com/tangram/view/?scene=https://raw.githubusercontent.com/ENT8R/streetcomplete-mapstyle/master/base-style.yaml)
* [Satellite](https://mapzen.com/tangram/view/?scene=https://raw.githubusercontent.com/ENT8R/streetcomplete-mapstyle/master/satellite-style.yaml)
* [Dark](https://mapzen.com/tangram/view/?scene=https://raw.githubusercontent.com/ENT8R/streetcomplete-mapstyle/master/dark-style.yaml)

P.S.: Those links will only work until the end of January if the urls are not changed...

**Comment by rugk** [comment]
Do we consider offering a satellite view for the user? (Generally not a bad idea, maybe, but the style does not fit here.)

And maybe the buildings are a bit too tall... Especially in big cities (as in the default in the test mode, New York) this looks a bit too tall.

**Comment by westnordost** [comment]
I wonder, how did @ENT8R create the preview images on the Readme.md? Perhaps, for show, and since it is not working anymore with mapzen preview, @ENT8R could also make pictures of the styles up-close (perhaps at Rödingsmarkt, Hamburg because it contains all elements)?

**Comment by ENT8R** [comment]
Tangram Play offers a "Take a screenshot" function...
Here are the images:
<img src="https://user-images.githubusercontent.com/25306497/35666365-044e2a86-072a-11e8-82e0-cd96078e0230.png">
<img src="https://user-images.githubusercontent.com/25306497/35666372-09882e02-072a-11e8-8e1b-d7afcd928813.png">
<img src="https://user-images.githubusercontent.com/25306497/35666375-0d7f9fea-072a-11e8-80ea-4d413e43c46d.png">

**Comment by matkoniecz** [comment]
I think that it is fixed (feel free to reopen if I missed something).

**Comment by rugk** [comment]
The night mode looks kinda futuristic. (with semi-transparent buildings and so on) Don't know if that is expected... 😉
