### ISSUE TITLE
Labels for waterways and water bodies

### ISSUE THREAD

**Issue by westnordost** [ENT8R/streetcomplete-mapstyle#80]
For orientation purposes, it might be helpful to display the names of waterways and water bodies.

Maybe instead of black with white frame, water-blue with white frame.

**Comment by matkoniecz** [comment]
https://github.com/matkoniecz/Zazolc/blob/fork/app/src/main/assets/map_theme/fork-style.yaml#L438
https://github.com/matkoniecz/Zazolc/blob/fork/app/src/main/assets/map_theme/fork-style.yaml#L460
may be useful where I tried to get useful name display for water features some time ago

**Comment by westnordost** [comment]
done

**Comment by ENT8R** [comment]
Currently waterways which are tunnels are completely filtered out:
https://github.com/ENT8R/streetcomplete-mapstyle/blob/e904c3c06017f4edb99638f6af0c6a20de3bd4b1/layers/land.yaml#L12-L14
Labels for these features are shown nevertheless, I guess it makes sense to also filter them. Or was this done on purpose @westnordost?

**Comment by westnordost** [comment]
Probably, yes
