### ISSUE TITLE
Do not display indoor ways

### ISSUE THREAD

**Issue by westnordost** [ENT8R/streetcomplete-mapstyle#81]
Since they can usually not be displayed properly on the map anyway but a dedicated indoor renderer is necessary, perhaps they should not be displayed at all.

**Comment by westnordost** [comment]
Or what do you think?

**Comment by matkoniecz** [comment]
indoor ways are not shown already as building transparency is not working (or is it just my phone?)

**Comment by westnordost** [comment]
Implemented for those schemas where the information is available
