### ISSUE TITLE
Addresses not displayed if tagged in building area

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/streetcomplete-mapstyle#82]
Not sure is it fixable

**Comment by westnordost** [comment]
Ohh, that's nasty! I sent them an email, I think it is a bug in the tiles generation of JawgMaps.

> I found an issue with JawgMaps that is very likely quite a nasty bug!
>
> On JawgMaps, it looks like this block has very few housenumbers mapped:
> https://www.jawg.io/en/maps#17.83/53.577027/9.941203
>
> However, looking at MapTiler, this is actually not the case:
> https://www.maptiler.com/maps/#streets//vector/17.83/9.941203/53.577027
> 
> Some addresses are mapped on the building outline here. For houses that have only one entrance, this is kind of standard, i.e. for detached houses.
> 
> Looking further, the issue runs deeper:
> 
> There is a Burger King here:
> https://www.maptiler.com/maps/#streets//vector/18.88/9.9373611/53.5783215
> 
> But it does not show on JawgMaps:
> https://www.jawg.io/en/maps#18.88/53.5783215/9.9373611
> 
> Likely this is the same issue: JawgMaps does not recognize POIs that are not point features.
>
> So, many amenities, shops and housenumbers are not shown on JawgMaps. Looking at taginfo, apparently over 50 million addresses (about 49% of all mapped addresses) are not shown because they are not mapped as points. Almost 1 million shops are not mapped as points, so they are also not shown. (Maybe) the same for amenities, tourist things, leisure things etc.?

**Comment by matkoniecz** [comment]
SC is less affected since question recently started mentioning house numbers where applicable (I even thought that it may be intentional to hide them from map).

**Comment by westnordost** [comment]
For orientation, housenumbers are very useful though

**Comment by matkoniecz** [comment]
I agree, that is why I reported it :)

**Comment by westnordost** [comment]
The answer was (important things in bold)

> You are talking about two different things. Housenumbers and POIs.
>
> You are right, for house numbers, we are taking only nodes (e.g node/3761820401), in your example, missing ones are on ways (e.g way/78143842).
> **This is something we can change, but I'm a bit worried about duplicates, sometimes we have house numbers on both ways and nodes for the same place...** 
>
> For POIs you can read our article here https://blog.jawg.io/introducing-new-icon-sets/.
> This is not about ways/nodes, in fact, we made the choice to have only neutral POIs on our maps (as explained in the blog article). That's why you will not see shops, restaurants....
> However transports, nature elements, public services, health services and education will be displayed whether they are points or ways in OSM.

to which I answered:

> This is usually visible when the POI (f.e. a shop) has an address and is within a building that has an address. If you leave out the address for POIs, only few duplicated house numbers will be left - mostly those that are "real" duplicates, i.e. could be considered as a mistake in various OpenStreetMap QA tools.

**Comment by tparcina** [comment]
> Not sure is it fixable

Why it would not be fixable?

**Comment by HolgerJeromin** [comment]
@TomislavParcina You can only display something which you know.
And it seems that the map data does not have this information in it.

**Comment by tparcina** [comment]
@HolgerJeromin And why map does not have this information in it? It seams that it gets various information from polygon (for example, is it a building or grass area), why it doesn't get address number information?

**Comment by HolgerJeromin** [comment]
Most map providers do not include every information that was entered in OSM. The file size would be much larger for information which is probably never needed.
This very ticket is about convincing the data provider (jawg) to include this information.

**Comment by michaelblyons** [comment]
> Most map providers do not include every information that was entered in OSM. The file size would be much larger for information which is probably never needed.

And nobody is suggesting they should do this. Jawg _already_ provides some house numbers, but only for points, not for polygons. StreetComplete, by contrast, often affixes house numbers to _buildings,_ which are typically polygons.

> This very ticket is about convincing the data provider (jawg) to include this information.

Yes. If you knew that, why did you say this:

> You can only display something which you know.  
> And it seems that the map data does not have this information in it.

**Comment by tparcina** [comment]
> Most map providers do not include every information that was entered in OSM. The file size would be much larger for information which is probably never needed.

I would not agree that address number is information which is probably never needed. If address number would be irrelevant, then it would not be provided for node either.

> This very ticket is about convincing the data provider (jawg) to include this information.

I believe that this ticket is about displaying address number no mater is it property of node or of polygon. Here should be identified why it does not display and how to fix it so that it becomes visible.

It seams that the reason why it is not visible is because map provider (jawg) does not include that information with is map. If that is correct, then I believe there are two options:
1. Ask map provider to include address number for polygon (just like it is included for node) or
2. Find another map provider that includes this information.

Best regards.

**Comment by westnordost** [comment]
https://github.com/ENT8R/streetcomplete-mapstyle/issues/82#issuecomment-650103434
https://github.com/ENT8R/streetcomplete-mapstyle/issues/82#issuecomment-654184629

**Comment by tparcina** [comment]
So, is this issue fixed? Are we now able to see house number if it is tagged on polygon?

**Comment by westnordost** [comment]
Yes, for v25.0-beta1 it is fixed

**Comment by tparcina** [comment]
Map provider now provides this information or you have changed map provider?

**Comment by westnordost** [comment]
Yes, see #88
