### ISSUE TITLE
Delete master branch, make nextzen the default branch

### ISSUE THREAD

**Issue by westnordost** [ENT8R/streetcomplete-mapstyle#83]
@ENT8R could you?

### Current situation:
jawg style is maintained on `jawg`
openmaptiles style is maintained on `openmaptiles `
thunderforest style is maintained on `thunderforest `
**nextzen style is maintained on `master`**

I think this is confusing as all the forks are (so far) all maintained equally. (Currently `jawg` is the one that is actually used by StreetComplete). 

### Change
So, the

**nextzen style should be maintained on `nextzen`**

and there is no reason to have a master at all.

**Comment by ENT8R** [comment]
Maybe, as StreetComplete (which is obviously the main user of this map style) now uses the tiles by Jawg, it would be more consistent to make `jawg` the default branch instead of `nextzen`?

**Comment by westnordost** [comment]
Maybe yes, but the problem is that that jawg requires an API key, so you would need to create yourself a jawg account to get a key for the demo site.

**Comment by ENT8R** [comment]
That should be no problem. I made `jawg` the default branch and updated the readme in all branches accordingly now

**Comment by westnordost** [comment]
Thanks!
