### ISSUE TITLE
Euston Road London rendered weirdly in dark mode 

### ISSUE THREAD

**Issue by peternewman** [ENT8R/streetcomplete-mapstyle#84]
As title. Needs more investigation.

It looks like a river almost semitransparent blue.

It seems to apply to highway=trunk and highway=motorway but not highway=motorway_link.

They look fine in the light mode.

**Comment by peternewman** [comment]
To me, switching to `blend: translucent` in `lines-highway-style` looks better, then optionally making the `highway_color` have some transparency.

**Comment by matkoniecz** [comment]
It looks weird also to me:

https://www.openstreetmap.org/#map=15/50.0879/19.8192&layers=N

![screen](https://user-images.githubusercontent.com/899988/97775056-a17a7e00-1b5d-11eb-9675-030c5ada255a.png)

Note, railways suffer from similar overlaps but far less severe ones.

**Comment by westnordost** [comment]
Even though this is kind of a bug in tangram-es, i think it looks quite cool

**Comment by peternewman** [comment]
> Even though this is kind of a bug in tangram-es, i think it looks quite cool

The longer overlap or the dots? It just seems a bit odd to me as it potentially has no or limited relevance to the road (e.g. change in lanes causing a dot).

**Comment by matkoniecz** [comment]
> Even though this is kind of a bug in tangram-es, i think it looks quite cool

For me it looks quite glitchy/confusing but also cool.

**Comment by westnordost** [comment]
One part of the bug is caused by 

https://tangrams.readthedocs.io/en/main/Syntax-Reference/draw/#cap

(cap: round)

tangram-es draws a round cap for each segment of a way, so at the point where there are two consecutive segments, two opposing round caps that complement each other become a circle.

**Comment by Helium314** [comment]
Looks less cool, but also a lot less weird/confusing when removing https://github.com/streetcomplete/streetcomplete-mapstyle/blob/2ecce80b365b2eea1e1351ad3abe5f8b355f9a5b/streetcomplete-dark-style.yaml#L46-L51
Very simple to test in https://streetcomplete.github.io/streetcomplete-mapstyle/?provider=jawg
The colors might then need some adjustment...

**Comment by westnordost** [comment]
Feel free to create a PR
