### ISSUE TITLE
Should underground waterways be displayed?

### ISSUE THREAD

**Issue by Scafir** [ENT8R/streetcomplete-mapstyle#85]
I do not think that they add much since there is to my knowledge no interaction possible and add noise on top of already dense zones.
Example at 46.53573,6.57065
P.S: Thank you for all your excellent work

**Comment by matkoniecz** [comment]
https://www.openstreetmap.org/#map=18/46.53573/6.57060

**Comment by westnordost** [comment]
So are they currently?

**Comment by matkoniecz** [comment]
Yes, this specific undeground waterway is displayed but I suspect external data corruption (at tile provider) as motorway is also incorrectly displayed at that location.

**Comment by westnordost** [comment]
Yes, tunnel / layer on the river is missing in jawg.

**Comment by Joxit** [comment]
Hi there, can you assign me to this issue ?

**Comment by westnordost** [comment]
Absolutely!

**Comment by Joxit** [comment]
`structure` properties for waterways is coming ! This will be available in tiles in 24~48 hours :smile:

**Comment by westnordost** [comment]
JawgMaps map style is getting better and better :-)

**Comment by ENT8R** [comment]
Thank you @Joxit for constantly improving Jawg vector tiles 🎉

---

<div align="center">
<h3>How it looked before...</h3>
<img src="https://user-images.githubusercontent.com/25306497/98399456-ae6a0680-2062-11eb-8c7c-b36d251be999.jpg" width="800px">
<h3>...and how it looks now</h3>
<img src="https://user-images.githubusercontent.com/25306497/98399448-aca04300-2062-11eb-96df-bc65f5931aa0.jpg" width="800px">
</div>

**Comment by Joxit** [comment]
Yeah, you're welcome 😁
