### ISSUE TITLE
Piers are not rendered

### ISSUE THREAD

**Issue by Etua** [ENT8R/streetcomplete-mapstyle#86]
Pretty much self-explanatory.

**Comment by ENT8R** [comment]
The outlines of piers solely tagged with `man_made=pier` seem to be included in the schemes of Nextzen, OpenMapTiles and Thunderforest. The only provider which does not include them is Jawg, so even if we would add it to the other stylesheets, it would not make its way into StreetComplete.
@westnordost, is it worth notifying Jawg for this potentially missing information? Elements which have a `highway=footway` tag next to `man_made=pier` are rendered nevertheless, so one could argue that the information is basically there, just the outline might be missing in some cases...

**Comment by westnordost** [comment]
I think it might. 

@Joxit : I'd say man made piers are in some places important for orientation as they are the defining feature for a harbour (or marina) area. Here are some places which have a lot of piers and thus may look odd on JawgMaps:

https://www.openstreetmap.org/#map=16/53.5435/9.9775
https://www.openstreetmap.org/#map=17/53.95875/10.87717
https://www.openstreetmap.org/#map=17/16.77268/96.14301

**Comment by Joxit** [comment]
Hi there, thank you for tagging me.
You are right, this is a interesting feature to add!
I will add this in my to-do list

**Comment by Joxit** [comment]
Can you add me in assignee?

**Comment by westnordost** [comment]
sure

**Comment by Joxit** [comment]
Hello, I just added man_mande=pier to our list. This should be visible in 24 to 48 hours. You will need to change your style, the new class is `bridge` with the type `pier` in `structure` layer.

Checkout [`structure`](https://www.jawg.io/docs/apidocs/maps/streets-v2/#structure) layer reference.
