### ISSUE TITLE
Increase the contrast for roads on farmland on the map

### ISSUE THREAD

**Issue by cyclingcat** [ENT8R/streetcomplete-mapstyle#87]
(According to https://github.com/westnordost/StreetComplete/issues/2092 it's an issue of the map style, hence this ticket here.)

Hi there,

would it be possible to increase the contrast for roads leading through farmland regions? The white roads with light brown roadsides are hardly visible on the yellow ground. 

See the screenshot (on the smartphone display it's actually much worse, especially under a bright sky):

![Screenshot_20200914-184155](https://user-images.githubusercontent.com/32601012/93602463-ee95fc80-f9c2-11ea-8e29-c5e3aedeef0d.png)

**Suggestion:**
Darken the colour of the farmland areas and/or blacken the borderlines of the roads.

(SC v22.3 on a Cubot Quest, Android 9.)

The cycling cat

**Comment by westnordost** [comment]
It is not possible to change the contrast for just farmland. It would need to be changed for all, either border width of the ways of color.

Dark mode is fine though?

Maybe you'd like to experiment yourself with what would be well visible for your eyes? See this project's readme on how to fiddle with the style

Am 18. September 2020 15:29:37 MESZ schrieb cyclingcat <notifications@github.com>:
>(According to https://github.com/westnordost/StreetComplete/issues/2092
>it's an issue of the map style, hence this ticket here.)
>
>Hi there,
>
>would it be possible to increase the contrast for roads leading through
>farmland regions? The white roads with light brown roadsides are hardly
>visible on the yellow ground. 
>
>See the screenshot (on the smartphone display it's actually much worse,
>especially under a bright sky):
>
>![Screenshot_20200914-184155](https://user-images.githubusercontent.com/32601012/93602463-ee95fc80-f9c2-11ea-8e29-c5e3aedeef0d.png)
>
>**Suggestion:**
>Darken the colour of the farmland areas and/or blacken the borderlines
>of the roads.
>
>
>(SC v22.3 on a Cubot Quest, Android 9.)
>
>The cycling cat

**Comment by cyclingcat** [comment]
Ok, I'll try it out, but not until my return from my holidays :smile_cat: Please leave this ticket open, at least until mid-October. (In dark mode the contrast is better, but all in all the colours of the areas are less intuitive than in normal mode.)

The cycling cat

**Comment by cyclingcat** [comment]
Hi there,

I just tried to play around with https://tangram.city/play/?scene=https://raw.githubusercontent.com/ENT8R/streetcomplete-mapstyle/jawg/streetcomplete-light-style.yaml linked from the project page, but I always get an error message _"Failed to load texture from https://raw.githubusercontent.com/ENT8R/streetcomplete-mapstyle/jawg/layers/oneway-arrow"_ (also with a brand new Firefox 81 profile, on Windows 8.1 Pro 64 Bit). Does it work for someone?

The URL https://raw.githubusercontent.com/ENT8R/streetcomplete-mapstyle/jawg/streetcomplete-light-style.yaml itself is reachable though and when I look into this file, I'd suspect that "road_outline_color" and "earth_color" would be the two parameters to be optimized.

So my first suggestion would be:

`road_outline_color: '#996666'`

in order to darken the road outline colour a little bit without breaking too much of the overall color scheme. If anyone has an idea how to get above Tangram Play URL running, I will do further tests.

The cycling cat

**Comment by westnordost** [comment]
> Does it work for someone?

No, don't mind that. It just means that the oneway-arrow cannot be loaded. The rest should load like normal.

A short instruction how to play around with the style:

1. Open https://play.tangram.city/?
2. copy & paste the contents of https://github.com/ENT8R/streetcomplete-mapstyle/blob/jawg/streetcomplete-light-style.yaml into the editor on the right side
3. you need a jawg api key. Go to https://jawg.io and register. After registering, in the "JawgLab" on the left, there is a tab called "Access tokens", copy the api token from there.
4. Add the following line below `global:` in the editor on trangram city: `    api_key: [paste your access token here]`
5. The map should render now. You can change the colors etc here, but not much more.
6. If you want to change more, in your case maybe the thickness of the road outline, remove the line that imports `https://raw.githubusercontent.com/ENT8R/streetcomplete-mapstyle/jawg/layers/roads.yaml` and instead copy&paste the contents of that file right into the editor (at the end). Note that you need to merge the contents of the `styles` caption, YAML does not allow duplicate keys
7. You can now edit everything regarding how roads are rendered

**Comment by cyclingcat** [comment]
Thank you for the explanation. So the problem was the missing key and not the error message as I originally assumed.

Now I played around with the parameters and would indeed vote for a darker "road outline color".

`road_outline_color: '#996666'`

or even

`road_outline_color: '#663333'`

looks good to me (at least on my PC screen), due to the much better contrast to the bright-yellow "earth color". Darkening the "earth color" wouldn't be necessary then, this would furthermore conflict too much with the "town color" which should remain darker than "earth color" IMHO.

The cycling cat

**Comment by westnordost** [comment]
Maybe you can add some screenshots?

**Comment by westnordost** [comment]
Did you try a thicker outline color? What about the outline color for paths?

**Comment by cyclingcat** [comment]
Here are some screenshots:

The current version:
![Current](https://user-images.githubusercontent.com/32601012/94583611-f20c6c00-027d-11eb-89d8-b5f27a7f4119.png)

With `road_outline_color: '#996666'`:
![996633](https://user-images.githubusercontent.com/32601012/94583619-f46ec600-027d-11eb-8a89-ab8e48189b31.png)

With `road_outline_color: '#663333'`:
![663333](https://user-images.githubusercontent.com/32601012/94583625-f6388980-027d-11eb-9b74-986e208265d3.png)

I'll try fiddling around with the thickness of the borders and paths soon (probably tomorrow).

The cycling cat

**Comment by westnordost** [comment]
The third certainly looks the clearest on farmland, however it seems a little too much contrast for other areas. Right now I would go with #996666.
Though path outline colors would need to be adapted too?

**Comment by cyclingcat** [comment]
Okay, further tests:

When I change the value of "path_outline_color", nothing happens, but changing "road_outline_color" changes the border colour of paths, too.  (In order to find paths on the map, I temporarily changed "path_color". This setting responds immediately, but changing "path_outline_color" has no effect.)

Concerning **borderline thicknesses**: I found the section where this is defined in roads.yaml:

```
        road-outline:
            filter: { $zoom: { min: 15 } }
            draw:
                lines:
                    outline:
                        color: global.road_outline_color
                        width: function () { return 1/4 * Math.log($zoom); }
                        order: 31
```

So the borderline is displayed only for zoom factors of 15 and above and its width depends on the zoom factor itself. See the following screenshots where I changed the numerator 1 in the formula of the "width" key ("road_outline_color" always set to '#996666'):

Numerator 1 (the current value):
![Numerator_10](https://user-images.githubusercontent.com/32601012/94661024-cc777500-0306-11eb-934b-8c8df14e3298.png)

Numerator 1.5:
![Numerator_15](https://user-images.githubusercontent.com/32601012/94661050-d4cfb000-0306-11eb-8f42-841701c42ec9.png)

Numerator 2:
![Numerator_20](https://user-images.githubusercontent.com/32601012/94661086-e2853580-0306-11eb-9ad5-709bc494f4d1.png)

As expected, the display of the roads/paths get clearer the higher the numerator is set. (There is a similar "path_outline" section, too, but like the "path_outline_color" section mentioned above has no effect on the borderline thicknesses of paths; the "road_outline" section works for paths as well.)

The cycling cat

**Comment by westnordost** [comment]
Of course the numerator 2 looks most clearest, but we may not forget that the map style is made for being "in the background", so the current low-contrast colors are deliberate. The map should not be too obstrusive. 

So as the one that had a problem even seeing the track lines on farmland on your smartphone with your eyes, what would you deem to be (the minimum) what is required for you to make out the tracks and orient yourself in the field?

**Comment by cyclingcat** [comment]
Granted, this is "only" a background map and never meant as a replacement for OsmAnd or similar tools. On the other hand, hardly visible ways/paths are of little help for the user. Maybe we find a combination of parameters which leads to the best of both worlds?

As soon as the sun starts shining again here (which may take some days...), I will go outside and try viewing this webpage with its many screenshots in order to get a feeling which parameters are a real improvement in terms of visibility.

As I am no Android expert: Would it be possible to replace above mentioned YAML files directly in the installed app on a non-rooted device? At least I found them inside the .apk file, so I am wondering if there is a way to copy my own versions of them for testing purposes without breaking anything - in this case I would be able to make screenshots directly from my device with quest icons over the map.

The cycling cat

**Comment by westnordost** [comment]
> As I am no Android expert: Would it be possible to replace above mentioned YAML files directly in the installed app on a non-rooted device?

No. You'd need to replace the files and then build yourself a debug version, deploy it on your phone.

But looking at this webpage with your phone in the sun may also do the trick.

Thanks!

**Comment by cyclingcat** [comment]
Pity. (Maybe I will be able to make such a debug version in some future...)

After all, I had the opportunity to test it with this webpage outside in yesterday's sunshine: The borderline thickness seems to have more effect on readibility of the roads/paths than the border colour, however, I haven't tested other (= darker) colours than those used in the screenshots above. A good compromise would be IMHO (only the changed lines mentioned):

```
road_outline_color: '#996666'

road-outline:
    draw:
        lines:
            outline:
                width: function () { return 1.5/4 * Math.log($zoom); }
```


The cycling cat

**Comment by westnordost** [comment]
OK! Would you like to create a PR for that? I'll merge it then
