### ISSUE TITLE
road outline handling

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/streetcomplete-mapstyle#9]
Note that on any crossing and astound any bridges probably unwanted outline appears

It may be fixed by giving outline lower layer than road filler

**Comment by matkoniecz** [comment]
Though rendering bridges is tricky, partially as result of https://github.com/tilezen/vector-datasource/issues/1314

**Comment by matkoniecz** [comment]
Would it be good enough to display in the same way

- road going on bridge over other road
- two roads crossing

And fix this bridge issue after upstream bug is fixed?

In that case I would be able to make a PR.

**Comment by westnordost** [comment]
Absolutely. There are many more intersections than bridges. It is more important that it looks good for the majority of cases.

**Comment by matkoniecz** [comment]
> Absolutely. There are many more intersections than bridges. It is more important that it looks good for the majority of cases.

done, PR made

**Comment by westnordost** [comment]
So this is done, insofar as it is fixable on our side, right?

**Comment by ENT8R** [comment]
I think yes. If there is still an issue it can be reopened...
