### ISSUE TITLE
Better distinguish [private] tracks visually

### ISSUE THREAD

**Issue by smichel17** [ENT8R/streetcomplete-mapstyle#90]
I was mapping recently, and could not walk the route I had planned because the way which I thought was a road (from the map style), was actually a private ~~path~~\* track with no obvious entrance (perhaps it was on the other side of the private property, but I did not want to walk across it to find out).

StreetComplete appearance:

<img height="500" src="https://user-images.githubusercontent.com/6563664/97087759-f0835900-161b-11eb-949f-5e807eca8796.png" alt="The track is a little bit narrower than the road it comes off of, but otherwise styled the same">

The way: https://www.openstreetmap.org/way/262940801#map=18/42.32343/-72.67034

Note I left: https://www.openstreetmap.org/note/2395716#map=17/42.32296/-72.67049

It would be useful to have a more-distinct style for tracks and/or private access only.

\*osm.org's styling for tracks made me think it was a path at first; I only happened to notice it was different when I was looking at the actual tags to see why it was not styled like the other paths nearby, that I have no trouble recognizing as not-roads. Turns out paths are rendered narrower than tracks. For comparison, at the same zoom level:

<img height="500" src="https://user-images.githubusercontent.com/6563664/97087928-0f361f80-161d-11eb-914f-710ce3247f0f.png" alt="this track"> <img height="500" src="https://user-images.githubusercontent.com/6563664/97087993-823f9600-161d-11eb-8259-0e421bed6ddd.png" alt="a (nearby) path">

**Comment by matkoniecz** [comment]
The relevant track is https://www.openstreetmap.org/way/262940801#map=18/42.32343/-72.67034

Note that there is already access styling, not sure is it not applied here due to missing data in tiles by Jawg or due to missing support in map style.

**Comment by smichel17** [comment]
Oops, I somehow mangled the link during copy-paste. Updated in my post as well

edit: also updated *another* place where I mistakenly called the track a path. "Track" is not part of my normal vocabulary (but now that I have the word in my head, I'm having trouble thinking of what I would normally call it).

**Comment by westnordost** [comment]
This is fixed since v25.0-beta1

This is how it looks in v25.0:

![Screenshot_20201025-000138_StreetComplete Dev](https://user-images.githubusercontent.com/4661658/97094492-5e984200-1655-11eb-95a0-20d954899fc3.jpg)
