### ISSUE TITLE
Move to StreetComplete?

### ISSUE THREAD

**Issue by westnordost** [ENT8R/streetcomplete-mapstyle#91]
I created a github organization "StreetComplete". Could we move this repo into the organization?

**Comment by ENT8R** [comment]
Done ✔️

**Comment by westnordost** [comment]
Are the commit rights etc all still correct?

**Comment by ENT8R** [comment]
Editing and committing files should work, but as far as I understand from reading [the official documentation](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization), I'm currently only having write privileges for this repository. Is it possible for you to grant me admin access to this repository, so I'm having the same rights as before?

**Comment by westnordost** [comment]
Oh, sure

**Comment by ENT8R** [comment]
Thank you
