### ISSUE TITLE
Render highway=platform

### ISSUE THREAD

**Issue by creideiki** [ENT8R/streetcomplete-mapstyle#92]
For roads where the pavements are mapped as separate ways with `highway=footway`, and bus stops being separate parts of the pavement ways tagged as `highway=platform`, StreetComplete does not render the bus stop at all. This is very confusing for the user, especially when there are quests for the pavement (e.g. which surface), which show up with a big hole in the middle.

Personally, I'm of the opinion that these bus stops, where the pavement is not special and the only real-world indication of its existence is a pole with a sign, should not be ways, but nodes tagged `highway=bus_stop`. However, this is apparently a minority opinion, at least in my local mapping community. Hence, please include rendering of ways with `highway=platform`.

See attached screenshots from StreetComplete and the OSM website for [an example bus stop](https://www.openstreetmap.org/way/426017497).
![streetcomplete](https://user-images.githubusercontent.com/1296902/101991502-68314400-3cad-11eb-8477-c9cbe43ef670.png)
![web](https://user-images.githubusercontent.com/1296902/101991505-6b2c3480-3cad-11eb-855d-d9a8c0295b6e.png)

**Comment by matkoniecz** [comment]
In this case it is a tagging mistake, `highway=footway` should not be interrupted in this way.

Displaying it like this is well representing what was (incorrectly) mapped here.

I opened https://www.openstreetmap.org/note/2460835
