### ISSUE TITLE
Inconsistent length of dashes at non-public track

### ISSUE THREAD

**Issue by Helium314** [ENT8R/streetcomplete-mapstyle#95]
The dashed outlines of private roads are usually rather consistent over different zoom levels, but I found one where the dashes change size considerably when zooming: https://www.openstreetmap.org/way/90858114
![dashes](https://user-images.githubusercontent.com/43007630/114981981-1bde5680-9e8f-11eb-919d-efe20d8074ee.png)

This seems really weird, at high zoom levels the dashes of just one part of the track are shorter than dashes on other parts of the same track.
(not sure if this really is a map style issue, might be tangram?)

**Comment by westnordost** [comment]
I can't imagine how this could be a mapstyle issue. Same issue with tangram? (Webgl version)?

On April 16, 2021 9:16:16 AM GMT+02:00, Helium314 ***@***.***> wrote:
>The dashed outlines of private roads are usually rather consistent over
>different zoom levels, but I found one where the dashes change size
>considerably when zooming: https://www.openstreetmap.org/way/90858114
>![dashes](https://user-images.githubusercontent.com/43007630/114981981-1bde5680-9e8f-11eb-919d-efe20d8074ee.png)
>
>This seems really weird, at high zoom levels the dashes of just one
>part of the track are shorter than dashes on other parts of the same
>track.
>(not sure if this really is a map style issue, might be tangram?)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/streetcomplete-mapstyle/issues/95

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Helium314** [comment]
Webgl version is this right: http://tangrams.github.io/tangram/#19.34999999999998/48.31867461182378/16.32980428061365
then: no issue with Webgl version

**Comment by Helium314** [comment]
Well, actually there is a different issue: the south-eastern half of the whole track is not displayed... no idea whether this is connected

**Comment by westnordost** [comment]
Yeah, if it is no issue with tangram but an issue with tangram-es, I'd say it is a tangram-es issue

On April 16, 2021 11:05:08 AM GMT+02:00, Helium314 ***@***.***> wrote:
>Well, actually there is a different issue: the south-eastern half of
>the whole track is not displayed... no idea whether this is connected
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/streetcomplete/streetcomplete-mapstyle/issues/95#issuecomment-821034218

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
Closing because there is now an issue upstream.
