### ISSUE TITLE
Satellite style: Should show roads and paths

### ISSUE THREAD

**Issue by westnordost** [ENT8R/streetcomplete-mapstyle#97]
In the satellite style, roads and paths should still be visible a bit, because certain quests depend on it. For example the cycleway quest, the sidewalk quest.

On satellite images, actual paths are often not visible when they are obscured by trees etc.

@matkoniecz 

could be similar to how Google Maps does it: Show the roads and paths in white but 90% alpha or something

**Comment by westnordost** [comment]
Is this something someone else would volunteer to do? This should be done before v32.0 hits the stable release (ETA: 2 weeks).

**Comment by ENT8R** [comment]
<p>Is this too obtrusive? Should there also be a separate variant for the dark theme?</p>
<div align=center>
    <h3>Before</h3>
    <img src="https://user-images.githubusercontent.com/25306497/115436891-cba72180-a20b-11eb-8a9b-4355aed3c3bb.jpg" width="750px">
    <h3>After</h3>
    <img src="https://user-images.githubusercontent.com/25306497/115437386-656ece80-a20c-11eb-8c8d-eefa357cb50c.png" width="750px">
</div>

**Comment by westnordost** [comment]
Wow nice!


I'd have removed the border, so it is only white but I don't know, I do like it like this. On the other hand, that bridge is also not a typical location. How does it look like in a residential area?

**Comment by westnordost** [comment]
Ah right, without the border, the information whether a way is private or not is lost, so it's good that the border is there too.

**Comment by westnordost** [comment]
I'd say that especially if the border is there to stay, then the alpha of the roads and paths themselves could be turned down a notch.

**Comment by westnordost** [comment]
Also, if the border is there to stay, does anything speak against keeping the color difference between the roads and paths (IIRC the paths were a little more orange)?

**Comment by ENT8R** [comment]
> does anything speak against keeping the color difference between the roads and paths

I don't know, maybe it would be helpful to increase the difference a little bit? Or would you rather remove the difference after all?

| road outline| path outline |
|  :---:  |  :---:  |
| ![#a88](https://via.placeholder.com/50/a88/000000?text=+) | ![#ca9](https://via.placeholder.com/50/ca9/000000?text=+) |

> How does it look like in a residential area?

![Screenshot_2021-04-20 streetcomplete-mapstyle](https://user-images.githubusercontent.com/25306497/115439431-dfa05280-a20e-11eb-8141-e6b2efdbefe8.jpg)

...and with reduced alpha value of the roads (0.3 instead of 0.5):
![Screenshot_2021-04-20 streetcomplete-mapstyle](https://user-images.githubusercontent.com/25306497/115441817-94d40a00-a211-11eb-9a28-0fb09d093995.jpg)

**Comment by matkoniecz** [comment]
@ENT8R If you will become stuck/busy/bored - let me know and I will complete it as part of satellite PR

Have you tested transparency on Android? I remember some bug related to that.

**Comment by westnordost** [comment]
0.3 alpha looks good!

**Comment by ENT8R** [comment]
> Have you tested transparency on Android? I remember some bug related to that. 

Transparency behaves and looks as expected on Android:

![Screenshot_20210421_213743](https://user-images.githubusercontent.com/25306497/115610986-d637e880-a2e9-11eb-8726-067c1ea41b5c.jpg)

**Comment by ENT8R** [comment]
@matkoniecz I just pushed the changes and gave you write access, so feel free to improve/change/fix anything. If you're done or don't see any improvements to be made, I will also update the other styles on the other branches. Though this could also wait, as StreetComplete only depends on Jawg as a provider...

**Comment by westnordost** [comment]
Tested on my phone, looks good! Thank you @ENT8R

**Comment by matkoniecz** [comment]
I would consider making rails thinner, especially tram rails (if doable in sane way)

https://www.openstreetmap.org/#map=19/50.07415/19.91061

![screen11](https://user-images.githubusercontent.com/899988/115991403-821e5400-a5c8-11eb-9213-27f157c263ff.png)

https://www.openstreetmap.org/#map=17/50.07513/19.94738

![screen12](https://user-images.githubusercontent.com/899988/115991446-b85bd380-a5c8-11eb-8f1c-e683dcd333cd.png)

**Comment by ENT8R** [comment]
Sorry for the late reply to your suggestion @matkoniecz 
Just to clarify, do you mean the displayed width of the railways or the opacity/transparency of them?

**Comment by matkoniecz** [comment]
likely both but with more focus on width
